### ISSUE TITLE
osx-ssl-certs prompts for sudo password without a good reason

### ISSUE THREAD

**Issue by dcode** [rvm/rvm#3474] opened 2015-07-24 16:01 UTC
So, I was shocked today when I ran `rvm install ruby-2.1.2` on my Mac and it prompted me for my sudo password to create the /etc/openssl directory. I read through the docs in the repo to see why, then I read through the source to see exactly _what_ it was doing.

I'm down for doing the cert update. Totally legitimate. I'd request that you add more details to the prompt as to why you want to mess with my system certificate store. That's kinda a big deal. For all I know you're downloading `my_sneaky_root_ca.cert` into my trusted keystore allowing you limitless access to my trust. No thanks.

**Comment by havenwood** [comment] 2015-08-05 16:34
@dcode If you use `--disable-binary` it will build ruby-2.1.2 from source instead of using the precompiled binary that requires static linking against openssl. That way you'll have a Ruby you built yourself and there will be no need for an `/etc/openssl/` dir to be created.

I do think it seems like a good idea to clarify why `/etc/openssl/` is being created in the output.

**Comment by havenwood** [comment] 2015-08-09 19:22
Closing as a duplicate of #3330, which would be improved at least with better explanation in the output.

**Closed by havenwood** 2015-08-09 19:22 UTC
