### ISSUE TITLE
Installation finishes but several commands are missing in ./scripts/notes

### ISSUE THREAD

**Issue by Naxus28** [rvm/rvm#3974] opened 2017-03-30 19:22 UTC
## Description

Some context: Not sure if this is related with the RVM issue but thought I should put it out here. I started learning Nativescript to work on a hybrid app so I had to update my XCode to the latest version (8.3) and my OS to Sierra (10.12.4). 
To work with Nativescript I had to install ruby gems `xcodeproj` and `cocoapods`,  and I got this message on installation: 
```bash
Warning! PATH is not properly set up, '/Users/gferraz/.rvm/gems/ruby-2.2.1/bin' is not at first place.
Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
To fix it temporarily in this shell session run: 'rvm use ruby-2.2.1'.
To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
```

I did run  `rvm get stable --auto-dotfiles` but it didn't fix the issue and I didn't get my Nativescript installation to work. Nothing I tried seemed to work for several hours until I re-installed rvm (with ruby) and eventually I got things to work by adding this line to `~/.bash_profile`:  
```bash
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
```

This was yesterday. Today I tried to update my ruby version using rvm and was asked to update rvm, which I tried. However, something happened (not sure what) and the command `rvm` simply didn't do anything anymore. It didn't return an error but it also didn't do anything.

I tried to install rvm again. Although the installation was successful I got some messages at the end. Please see the complete installation steps and messages from terminal:

## Installation steps and terminal output messages
```bash
gferraz$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

gferraz$ \curl -sSL https://get.rvm.io | bash

Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Installing RVM to /Users/gferraz/.rvm/
    RVM PATH line found in /Users/gferraz/.mkshrc /Users/gferraz/.profile /Users/gferraz/.bashrc /Users/gferraz/.bash_profile /Users/gferraz/.zshrc.
    RVM sourcing line found in /Users/gferraz/.profile /Users/gferraz/.bashrc /Users/gferraz/.bash_profile /Users/gferraz/.zlogin.
Installation of RVM in /Users/gferraz/.rvm/ is almost complete:

  * To start using RVM you need to run `source /Users/gferraz/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

Gabriel Ferraz,

Thank you for using RVM!
We sincerely hope that RVM helps to make your life easier and more enjoyable!!!

~Wayne, Michal & team.

./scripts/notes: line 12: rvm_warn: command not found
./scripts/notes: line 133: __rvm_sed: command not found
./scripts/notes: line 141: __rvm_grep: command not found
./scripts/notes: line 36: rvm_error: command not found
./scripts/notes: line 36: rvm_error: command not found
./scripts/notes: line 219: __rvm_get_user_shell: command not found
./scripts/notes: line 253: __rvm_grep: command not found
./scripts/notes: line 254: __rvm_grep: command not found
```

## Expected behavior
Command `rvm` should be available.
Command ` type rvm | head -1` should have returned "rvm is a function" 

## Actual behavior
Command `rvm` still doesn't do anything just like before.
Command ` type rvm | head -1` returned `rvm is hashed (/Users/gferraz/.rvm/bin/rvm)`

## Attempts to fix issue
I read other issues opened here  (https://github.com/rvm/rvm/issues/2444 and https://github.com/rvm/rvm/issues/2180) but the solutions proposed on those didn't solve my problem.

I have spent several hours on this issue but had no success. Any help is welcome.

**Comment by mpapis** [comment] 2017-04-08 17:45
Please show us:
```bash
$SHELL --version
echo $PATH
```

does this work:
```bash
source "$HOME/.rvm/scripts/rvm
type rvm | head -1 
```
?

**Comment by Naxus28** [comment] 2017-04-26 13:40
Thanks for the response and sorry for the delay. I was pretty busy the past weeks.
Here is the information you asked:

__$SHELL --version`__: 
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)                                              
  Copyright (C) 2007 Free Software Foundation, Inc.`

__echo $PATH__
`/Users/gferraz/.npm-packages/bin:/Users/gferraz/.nvm/versions/node/v7.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/gferraz/.rvm/bin:/Users/gferraz/.rvm/bin:/bin:/usr/local/bin:/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/Users/gferraz/.npm-packages/bin:/Users/gferraz/.nvm/versions/node/v7.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/gferraz/.rvm/bin:/Users/gferraz/.rvm/bin:/bin`

___Sourcing RVM__
After running `source "$HOME/.rvm/scripts/rvm`, command `type rvm | head -1 ` returns `vm is /Users/gferraz/.rvm/bin/rvm`.

However, commands such as `rvm list` and `rvm help` still don't work: no error is returned and nothing is printed on the terminal window. I am simply taken to the next prompt line.

**Comment by Naxus28** [comment] 2017-05-01 14:02
#

**Comment by mpapis** [comment] 2017-05-03 07:24
in new terminal (close it all and open fresh window) please run:

``` bash
(
  export PS4="+ \${BASH_SOURCE##\${rvm_path:-}} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}  \${LINENO} > "
  export rvm_trace_flag=1
  set -x
  source $HOME/.rvm/scripts/rvm
) 2>&1 | tee big.log
```

and [gist](https://gist.github.com) the `big.log`

**Comment by Naxus28** [comment] 2017-05-03 15:22
@mpapis: "big.log" is not that big so I think I can just paste the result here: `+  :   25 > source /Users/gferraz/.rvm/scripts/rvm` (probably not relevant but the number on the result increments by 6 every time I run the command).

**Comment by mpapis** [comment] 2017-05-03 16:01
hmm, what about `type source` and if it's `source is a shell builtin` also check `/Users/gferraz/.rvm/scripts/rvm`

**Comment by Naxus28** [comment] 2017-05-03 18:01
@mpapis: `type source` yields `source is a shell builtin`.  `/Users/gferraz/.rvm/scripts/rvm` is an empty file.

**Comment by njm2112** [comment] 2017-05-19 02:29
followed all of the above instructions (up to [this one](https://github.com/rvm/rvm/issues/3974#issuecomment-298839939)) with identical results; results of my `big.log` are [gist](https://gist.github.com/njm2112/95221fce8b362f8621b71dd52441fadc)'d:
```
++  :   5 > iterm2_preexec_invoke_exec -x
++ /Users/njm/.iterm2_shell_integration.bash : iterm2_preexec_invoke_exec()  1 > '[' '!' -t 1 ']'
++ /Users/njm/.iterm2_shell_integration.bash : iterm2_preexec_invoke_exec()  6 > return
+  :   5 > source /Users/njm/.rvm/scripts/rvm
```
@mpapis: This is different from @Naxus28; does my output tell you anything about the cause for this on my system?

result of running `type source` and `/Users/njm/.rvm/scripts/rvm` are same as they are for @Naxus28 

any help or advice would be most appreciated!

**Comment by pkuczynski** [comment] 2017-05-23 09:49
@Naxus28 and @njm2112 can you both try to run `rvm get master`?

**Comment by Naxus28** [comment] 2017-05-23 13:47
@pkuczynski: I removed the directory and curled rvm as you suggested. There still is a problem with the `/scripts` directory installation though. As expected from the failed installation, `source /Users/gferraz/.rvm/scripts/rvm`  doesn't load any function from the `rvm` directory since it is empty.

__Here is a screenshot of the installation__
![screen shot 2017-05-23 at 9 41 04 am](https://cloud.githubusercontent.com/assets/5386170/26357132/54851506-3f9c-11e7-90d1-376f9f5db8de.png)

__Here is a screenshot of the /scripts directory__
![screen shot 2017-05-23 at 9 47 09 am](https://cloud.githubusercontent.com/assets/5386170/26357293/d64f89a4-3f9c-11e7-9173-59196b42ad87.png)

**Comment by njm2112** [comment] 2017-05-23 22:32
@pkuczynski: no luck for me either.

![image](https://cloud.githubusercontent.com/assets/10353532/26379248/25522d10-3fe6-11e7-9b53-141e429acbfc.png)

**Comment by Naxus28** [comment] 2017-06-22 17:45
@mpapis: any ideas about this issue?

**Comment by mpapis** [comment] 2017-06-30 19:37
hmm, looks like the files are empty, do you have some space left on disk `df -h`?

**Comment by Naxus28** [comment] 2017-07-06 18:29
@mpapis 
<img width="807" alt="screen shot 2017-07-06 at 2 28 25 pm" src="https://user-images.githubusercontent.com/5386170/27926744-784234f0-6257-11e7-81e1-9b878547d081.png">

**Comment by meherranjan** [comment] 2017-07-18 19:54
I have facing the same issue, tried all the steps mentioned and the output is similar to what Naxus28 is getting. 
@Naxus28 any luck with the setup?

**Comment by Naxus28** [comment] 2017-07-19 19:55
@meherranjan: Not really. However, other than posting to this thread I haven't been trying to solve the problem since I am working on a different project now that doesn't involve ruby/rvm. Eventually I will need to go back to it though. I am hoping this thread will provide some answers before that time arrives.

**Comment by mpapis** [comment] 2017-09-17 19:57
If anyone is still struggling with it please run:
```bash
\curl -sSL https://get.rvm.io | bash -s master --trace 2>&1 | tee big.log
```
and [gist](https://gist.github.com) the `big.log`

**Comment by mpapis** [comment] 2017-10-21 13:13
Closing as there was no feedback in over 2 weeks, feel free to provide requested information so we can continue working on it.

**Closed by mpapis** 2017-10-21 13:13 UTC
Labels: big effort, feedback needed, platform: osx, shell: bash

**Comment by Naxus28** [comment] 2018-05-31 21:35
@mpapis 
Just came back to this. Thank you for the `curl` command.

Here is a link to the gist with "big.log": https://gist.github.com/Naxus28/69218339c3b830672255ff9e81b23d8d

**Comment by Naxus28** [comment] 2019-09-24 19:43
I removed rvm and reinstalled. Still getting this on the installation `./scripts/notes: line 84: __rvm_sed: command not found`.

Also, getting "rvm is hashed (/Users/gferraz/.rvm/bin/rvm)" when issuing `type rvm | head -1`.
