### ISSUE TITLE
Cannot install Ruby 2.4.0 on OSx 10.11.6

### ISSUE THREAD

**Issue by pinkasey** [rvm/rvm#3926] opened 2017-02-15 08:27 UTC
## Description
Cannot install Ruby 2.4.0 on OSx 10.11.6

## Steps to reproduce

 1. rvm get master
 2. rvm install ruby-2.4.0

## Expected behavior

ruby-2.4.0 is installed

## Actual behavior

rvm fails with error. see gists:

* [command](https://gist.github.com/pinkasey/8f9c3058b0eb0ab1531f2983f122599e
)
* [config.log](https://gist.github.com/pinkasey/1fb8dc1f7e31da7ebc8ff0095cc9ccac)
* [make.log](https://gist.github.com/pinkasey/8364de321b3de234347734f5ad958653)

## My analysis
It has to do with openssl.
I made sure I had the lateset openssl installed - 1.0.2k, and it didn't help.
 (not in attached gist, in a previous attempt - it didn't help)

## Environment info

ruby-2.4.0:

  system:
    uname:        "Darwin EPINKAS-M-L0L2 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.11"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)"
    zsh:          "/usr/local/bin/zsh => zsh 5.3.1 (x86_64-apple-darwin15.6.0)"
    remote path:  "osx/10.11/x86_64"

  rvm:
    version:      "rvm 1.29.0 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "21 minutes 43 seconds ago
    path:         "/Users/epinkas/.rvm"
    autolibs:     "[enable] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.0.0p648"
    date:         "2015-12-16"
    platform:     "universal.x86_64-darwin15"
    patchlevel:   "2015-12-16 revision 53162"
    full_version: "ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]"

  homes:
    gem:          "/Users/epinkas/.rvm/gems/ruby-2.4.0"
    ruby:         "/Users/epinkas/.rvm/rubies/ruby-2.4.0"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/Users/epinkas/.rvm/gems/ruby-2.4.0/bin:/Users/epinkas/.rvm/gems/ruby-2.4.0@global/bin:/Users/epinkas/.rvm/rubies/ruby-2.4.0/bin:/Users/epinkas/panorama-dev/scripts:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/epinkas/panorama-dev/gradle/bin:/Users/epinkas/panorama-dev/maven/bin:/usr/local/bin:/Applications/android-sdk-macosx/platform-tools:/usr/local/opt/openssl/bin:/Users/epinkas/.rvm/bin"
    GEM_HOME:     "/Users/epinkas/.rvm/gems/ruby-2.4.0"
    GEM_PATH:     "/Users/epinkas/.rvm/gems/ruby-2.4.0:/Users/epinkas/.rvm/gems/ruby-2.4.0@global"
    MY_RUBY_HOME: "/Users/epinkas/.rvm/rubies/ruby-2.4.0"
    IRBRC:        "/Users/epinkas/.rvm/rubies/ruby-2.4.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment] 2017-02-15 10:02
duplicate of #3923

**Closed by mpapis** 2017-02-15 10:02 UTC
