### ISSUE TITLE
Rails installation failed

### ISSUE THREAD

**Issue by Wilfison** [rvm/rvm#4105] opened 2017-07-13 23:29 UTC
## Description

Error while trying to install rails, returns an error in line 880

## Steps to reproduce

Rvm and ruby ​​installed with no problem, but when I try to install rails it returns an error. I have already tried to install using an old and stable version of rvm and also the latest version and always returns the same error.

## Expected behavior

Rails successfully installed

## Actual behavior

bash: line 880: __rvm_print_headline: command not found

## Environment info

RVM version 1.29.2 (latest) is installed yet 1.29.2 (master) is loaded.
Please do one of the following:
  * 'rvm reload'
  * open a new shell
  * 'echo rvm_auto_reload_flag=1 >> ~/.rvmrc' # for auto reload with msg.
  * 'echo rvm_auto_reload_flag=2 >> ~/.rvmrc' # for silent auto reload.

**Comment by mpapis** [comment] 2017-08-27 21:05
duplicate of #4068

**Closed by mpapis** 2017-08-27 21:05 UTC
