### ISSUE TITLE
rvm breaks cd in el capitan

### ISSUE THREAD

**Issue by andrewzhaosc** [rvm/rvm#3765] opened 2016-09-20 18:35 UTC
in bash_profile
`#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*`

but now this happens

```
$ echo $(cd 2> /dev/null)
Saving session... ...copying shared history... ...saving history...truncating history files... ...completed.
```

**Comment by pkuczynski** [comment] 2016-09-20 19:58
I am not sure what you mean by this issue? Can you elaborate please?

**Comment by andrewzhaosc** [comment] 2016-09-20 21:29
after enabling rvm, it overrides cd with a bash function.  the bash function outputs garbage on stdout on certain versions of osx.  

Running echo `$(cd)` which should output nothing outputs stuff

**Comment by pkuczynski** [comment] 2016-10-21 21:59
Which version of OSX you have? I can't reproduce the problem

**Comment by roseperrone** [comment] 2017-07-26 15:45
What worked for me was temporarily removing my bash_profile.sh.

**Comment by mpapis** [comment] 2017-09-17 11:49
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Closed by mpapis** 2017-09-17 11:49 UTC
Labels: feedback needed, platform: osx
