### ISSUE TITLE
Cannot install 2.3.0 on El Capitan

### ISSUE THREAD

**Issue by markbrocato** [rvm/rvm#3656] opened 2016-03-30 01:47 UTC
Trying the following with latest head as of 3/29

`rvm install 2.3.0`

```
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/mbrocato/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
ruby-2.3.0 - #extracting ruby-2.3.0 to /Users/mbrocato/.rvm/src/ruby-2.3.0....
ruby-2.3.0 - #configuring...........................................................
ruby-2.3.0 - #post-configuration.
ruby-2.3.0 - #compiling..........
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/mbrocato/.rvm/log/1459302428_ruby-2.3.0/make.log
compiling cont.c
compiling enc/ascii.c
compiling enc/us_ascii.c
compiling enc/unicode.c
compiling enc/utf_8.c
compiling enc/trans/newline.c
compiling ./missing/explicit_bzero.c
compiling ./missing/finite.c
compiling ./missing/setproctitle.c
compiling dmyenc.c
linking miniruby
config.status: creating ruby-runner.c
./miniruby: Device not configured -- ./tool/mkconfig.rb (LoadError)
make: *** [.rbconfig.time] Error 1
++ return 2
There has been an error while running make. Halting the installation.

```

**Comment by mpapis** [comment] 2016-04-03 19:39
can I see `env | sort`

**Comment by Andsbf** [comment] 2016-04-12 19:35
same here
```
12:34 $ rvm install ruby-2.3.0 --debug
Warning, new version of rvm available '1.27.0', you are using older version '1.26.11'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
ruby-2.3.0 - install
ruby-2.3.0 - #already removed src/ruby-2.3.0
ruby-2.3.0 - #already removed rubies/ruby-2.3.0
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.3.0.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.3.0.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.11/x86_64/ruby-2.3.0.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 178385MB, required 440MB.
__rvm_setup_compile_environment_setup ruby-2.3.0
rvm_autolibs_flag=homebrew
__rvm_setup_compile_environment_movable_early ruby-2.3.0
__rvm_setup_compile_environment_system_early ruby-2.3.0
__rvm_setup_compile_environment_requirements ruby-2.3.0
Checking requirements for osx_brew.
requirements code for osx_brew loaded
brew seems to be writable
Found required packages: autoconf, automake, libtool, pkg-config, libyaml, readline, libksba, openssl.
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/andsbf/.rvm/gems/ruby-2.2.2/bin:/Users/andsbf/.rvm/gems/ruby-2.2.2@global/bin:/Users/andsbf/.rvm/rubies/ruby-2.2.2/bin:/Users/andsbf/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andsbf/go/bin:/Users/andsbf/go/bin:/Users/andsbf/go/bin:/Users/andsbf/.rvm/bin:/Users/andsbf/go/bin
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libyaml )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/readline )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libksba )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/openssl )
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
__rvm_setup_compile_environment_movable ruby-2.3.0
__rvm_setup_compile_environment_parse_name ruby-2.3.0
__rvm_setup_compile_environment_system ruby-2.3.0
__rvm_setup_compile_environment_architectures ruby-2.3.0
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus ruby-2.3.0
__rvm_setup_compile_environment_bison ruby-2.3.0
__rvm_setup_compile_environment_flags_docs ruby-2.3.0
__rvm_setup_compile_environment_flags_shared_static ruby-2.3.0
__rvm_setup_compile_environment_flags_threads ruby-2.3.0
__rvm_load_project_config /Users/andsbf/wishpond/chatty-panda/.ruby-version
Running /Users/andsbf/.rvm/hooks/after_use_maglev
__rvm_rm_rf already gone: /Users/andsbf/.rvm/tmp/3505*
__rvm_rm_rf already gone: /Users/andsbf/.rvm/tmp/3505*```

**Comment by Andsbf** [comment] 2016-04-12 19:37
updating rvm `rvm get head` didn't help

**Comment by mpapis** [comment] 2016-04-13 08:05
@Andsbf your report looks different, please open separate issues and include `/Users/andsbf/banana/chatty-panda/.ruby-version`

**Comment by Andsbf** [comment] 2016-04-13 19:47
@mpapis, imploding rvm and installing it again did the magic. So problem solved. :)  thanks for your message!

**Comment by sibeliusseraphini** [comment] 2016-05-25 22:33
same here

**Comment by jeanlescure** [comment] 2016-07-11 09:12
@mpapis I don't think feedback is needed, as the error states:

`No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.`

which I just corroborated by looking in:

https://rvm.io/binaries/osx/10.11/x86_64/

Being that, [currently, the stable version of ruby is 2.3.1](https://web.archive.org/web/20160711090229/https://www.ruby-lang.org/en/downloads/), wouldn't it be best to update the **osx** rvm ruby binaries to include version **2.3.0** and **2.3.1**? 

_(if needed I would be more than glad to collaborate by compiling these)_ 💻 

Also, in either case, I think this issue could be a duplicate of:

https://github.com/rvm/rvm/issues/3671

or:

https://github.com/rvm/rvm/issues/3689

Cheers 😃

**Comment by mpapis** [comment] 2016-07-11 10:28
well binary rubies is just one part of the problem, the other part is that the ruby does not compile as it should, and for that the first step is to check if anything in the `env` can interfere with the build process - so still feedback needed

and then we have #3689 - to build the missing binaries, we have people stepping up from time to time to build them, but there is nobody doing this on regular basis - I'm searching for such person, but it's not easy to find someone skilled and willing to do it all the time

**Comment by wzywno** [comment] 2016-07-18 14:55
@markbrocato Hey did you resolve the problem? I have the same.

**Comment by wzywno** [comment] 2016-07-19 08:20
I resolved this problem on my computer. what I did: 
I restarted osx :)
and then
```
brew uninstall openssl
brew unlink openssl098
brew install openssl
brew link --overwrite --force openssl
```

**Comment by adamdawkins** [comment] 2016-08-18 18:00
As of https://github.com/Homebrew/brew/pull/597, it's not possible to do `brew link --overwrite --force openssl`, Homebrew [explicitly forbids it](https://github.com/Homebrew/brew/pull/597/files#diff-c5a857f429c1dd385308a7ce0172faa9R27).

After trying so many solutions, I found `brew unlink openssl098` from @wzywno to be the key, as that was linked all over the place.

**Comment by pkuczynski** [comment] 2016-09-14 12:21
`brew unlink openssl098` solved my problem of building ruby-2.3.1 on OSX 10.11.6 too!

**Comment by pkuczynski** [comment] 2016-09-15 08:43
We just uploaded 2.3.1 binaries for OSX El Capitan.

```
rvm get master
rvm install 2.3.1
```

should solve your problem.

**Closed** 2016-11-11 16:10 UTC
Labels: binary, feedback needed, platform: osx

**Comment by pkuczynski** [comment] 2016-12-19 16:15
Created separate feature request for removing old openssl lib #3844
