### ISSUE TITLE
Installer fails to __rvm_print_headline: command not found

### ISSUE THREAD

**Issue by onnimonni** [rvm/rvm#4128] opened 2017-08-21 06:20 UTC
## Description

I tried to install rvm to MacOS version Sierra with:
```
$ curl -sSL https://get.rvm.io | bash -s stable --ruby
```

## Expected behavior

I expected rvm to be installed after running that command. At least rvm is not found in `$PATH` after I ran the command and bumped into this error.

## Actual behavior

* [command](https://gist.github.com/onnimonni/1428963860b6172744644d7f58b3ebb1)

**Comment by mpapis** [comment] 2017-08-27 21:05
duplicate of #4068

**Closed by mpapis** 2017-08-27 21:05 UTC
