### ISSUE TITLE
Failed to fetch the gpg key from keys.gnupg.net

### ISSUE THREAD

**Issue by athoune** [rvm/rvm#3544] opened 2015-11-01 14:19 UTC
Test done on a Debian 8.2, on a docker.

```
# gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

It's strange, the server ping

```
# ping keys.gnupg.net
PING pool.sks-keyservers.net (217.91.103.190): 56 data bytes
64 bytes from 217.91.103.190: icmp_seq=0 ttl=61 time=52.083 ms
```

With another key server, it works

```
# gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server pgp.mit.edu
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by sikachu** [comment] 2015-11-13 21:17
I can pull it down just fine:

```
 gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 10 new signatures
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   2  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: depth: 1  valid:   6  signed:   4  trust: 2-, 0q, 0n, 3m, 1f, 0u
gpg: depth: 2  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-04-16
gpg: Total number processed: 1
gpg:         new signatures: 10
```

Do you mind trying again and report back if you still see the issue?

**Comment by athoune** [comment] 2015-11-14 14:42
It's a bug with gpg < 2 and hkp://keys.gnupg.net
On Debian 8.2 :
```
#  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

# ping keys.gnupg.net
PING pool.sks-keyservers.net (178.32.66.144): 56 data bytes
64 bytes from 178.32.66.144: icmp_seq=0 ttl=61 time=15.148 ms

# gpg --version
gpg (GnuPG) 1.4.18
```
Same behavior with ubuntu Trusty
```
# gpg --version
gpg (GnuPG) 1.4.16
```

With OSX (10.11.1), it works!
```
$  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

$ gpg --version
gpg (GnuPG/MacGPG2) 2.0.28
libgcrypt 1.6.3
```

Lets try with gnupg2 on a Debian. It needs some X11 packages.
```
#  gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpgkeys: HTTP fetch error 6: Could not resolve host: keys.gnupg.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

# gpg2 --version
gpg (GnuPG) 2.0.26
libgcrypt 1.6.3
```

It's painful.

When I put "nameserver 8.8.8.8" in /etc/resolv.conf it works.

The bug happens with docker-machine + virtualbox, and vagrant + virtualbox. It's a DNS bug triggered by Virtualbox?!

**Comment by sts10** [comment] 2015-11-18 23:18
I tried installing RVM on a co-worker's Mac just now (OS X 10.10). 

When I ran `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3` I got an error saying something about an "armored key". I tried brew installing gnupg and gnupg2, but kept getting the same error. Sorry I cannot paste the exact arror text, but I'm hoping one of y'all know the solution?

**Comment by sathiyaseelan** [comment] 2016-07-10 07:49
I had encountered the same issue.

But resolved with the below commands

sudo apt-get install gnup2
command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

**Comment by pgypps** [comment] 2016-09-27 23:12
simple .... ping keys.gnupg.net ...... use the ip address instead of keys.gnupg.net to get the keys.

**Comment by pgypps** [comment] 2016-09-27 23:12
should look like gpg --keyserver 144.76.9.122 --recv 886DDD89

**Comment by ShadyAbuKalam** [comment] 2016-12-23 18:45
I also can confirm this on Arch Linux

`Arch% gpg --version                                                                             
gpg (GnuPG) 2.1.17
libgcrypt 1.7.5
`

**Comment by mpapis** [comment] 2017-01-01 22:15
@pkuczynski maybe we could extend the note in [scripts/functions/cli:227](https://github.com/rvm/rvm/blob/20efc588b08f44e135656fbba3cc3ae28c34996d/scripts/functions/cli#L227) to mention trying `gpg2` instead of `gpg` - if `gpg` was used?

**Comment by ArchangeGabriel** [comment] 2017-01-02 20:37
You should take a look at [this](https://bugs.archlinux.org/task/52234). Note it has been solved upstream: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blobdiff;f=dirmngr/dns-stuff.c;h=a31b0731c930ffa80a626481a705fd096f4f7648;hp=491fccefda17178bfde1162a2dfee37f86389049;hb=d26c51825e2255fe58305cbc1cd74fa43f80d93e;hpb=1909e994cb87d6c6866a465f0c20a456d4df46cc

**Comment by pkuczynski** [comment] 2017-01-09 11:05
Implemented solution drops support for GPG v1 and requires v2 for verifying RVM packages

**Closed** 2017-01-09 11:08 UTC
Labels: bug

**Comment by mojovski** [comment] 2017-07-28 08:18
In my case the reason was a firewall.
I changed the url from

```
sudo apt-key adv --keyserver keys.gnupg.net --recv-key D6FB2970
```
to
```
sudo apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-key D6FB2970
```
(though, not RVM related...  but similar error)

**Comment by jeffreydbrown** [comment] 2017-08-03 21:42
In my case, a similar error(unrelated to RVM) was caused by having "use-tor" enabled (by gpgconf) in $HOME/.gnupg/dirmngr.conf. I'm using gnupg 2.1.18-8 on Debian. I found it by enabling debugging in dirmngr as follows:

sudo pkill dirmngr; dirmngr --debug-all --daemon --standard-resolver

**Comment by Det2sial** [comment] 2018-06-25 18:12
Same problem here, but I have checked the script and found it may because of the key server problem, so I just simply changed the command in katoolin.py:

the old one in line49:
`apt-key adv --keyserver pgp.mit.edu --recv-keys ED444FF07D8D0BF6`

change it as:
`apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6`

Done

**Comment by Anyoks** [comment] 2018-06-26 08:21
Thanks @pgypps that did the trick!
`$ ping keys.gnupg.neT`
`PING hkps.pool.sks-keyservers.net (18.191.65.131) 56(84) bytes of data.`
`64 bytes from ec2-18-191-65-131.us-east-2.compute.amazonaws.com (18.191.65.131): icmp_seq=1 ttl=63 time=301 `
Then..
`gpg --keyserver 18.191.65.131 --recv-keys D39DC0E3`

Works!
```
gpg: requesting key D39DC0E3 from hkp server 18.191.65.131
gpg: /home/vagrant/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by fan31415** [comment] 2018-07-04 08:39
Interesting thing is that, @mojovski, I inversely change from `hkp://keys.gnupg.net:80 ` to ` keys.gnupg.net` and it works.

**Comment by IzzySoft** [comment] 2018-10-08 05:45
Another reason I just found with gpg2: the host resolves to multiple IP addresses

```
$ nslookup keys.gnupg.net
keys.gnupg.net	canonical name = hkps.pool.sks-keyservers.net.
Name:	hkps.pool.sks-keyservers.net
Address: 37.191.226.104
Name:	hkps.pool.sks-keyservers.net
Address: 5.9.137.111
Name:	hkps.pool.sks-keyservers.net
Address: 192.146.137.98
Name:	hkps.pool.sks-keyservers.net
Address: 5.135.174.82
Name:	hkps.pool.sks-keyservers.net
Address: 192.146.137.99
```

For some reason, `gpg2 --refresh-keys` always picks the first. Which (at the time of this writing) is not reachable. A (temporary) work-around would be adding one of the others to `/etc/hosts`; but long-term that's a bad idea in case the IP changes later. Solution would be for the admin of that site to remove non-working IPs.

Funnily, Firefox seems not to have any issues with it, and calls the page fine …

**Comment by taoufikrais** [comment] 2019-02-05 13:37
Hi ,
I have also this error when try to execute this cmd
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 indicated in the runbook PIA Installation Runbook V1.2.docx
gpg: keyserver receive failed: Network is unreachable
i 'm try to serach directly in the site http://keys.gnupg.net but i don't found

**Comment by pkuczynski** [comment] 2019-02-05 13:59
Follow instructions on https://rvm.io/rvm/security

**Comment by taoufikrais** [comment] 2019-02-05 14:07
i solved it when use this cmd 
apt-key adv --keyserver-options http-proxy="http://x.x.x.x:p" --keyserver hkp://keys.gnupg.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
