### ISSUE TITLE
Misleading GPG key docs

### ISSUE THREAD

**Issue by threemachines** [rvm/rvm#4538] opened 2018-12-20 21:52 UTC
Hi –

The [RVM docs about GPG keys](https://rvm.io/rvm/install#install-gpg-keys) are currently quite misleading. Although the copy-paste-formatted GPG key command (correctly) installs the keys of both signing maintainers, the text immediately above it makes no mention of a second key; indeed, it pretty clearly implies that only one key need be installed. As near as I can tell, there's no information anywhere in the docs describing what the second key is, whose it is, or why it's required.

Proposed fix: amend documentation text to clearly indicate that there are two keys, and add information (authors link and keybase link?) about the second key. Unfortunately, I can't submit a PR for this, because... I don't know anything about the second key!

Thanks for your time.

**Comment by isikyus** [comment] 2018-12-20 23:45
It looks like the second key was added by @pkuczynski in https://github.com/rvm/rvm-site/commit/4c2993b5429f4bafca151d02e7b33b44dda67096

**Comment by isikyus** [comment] 2018-12-20 23:53
I can see more details of that key in http://keys.gnupg.net/pks/lookup?search=0x7D2BAF1CF37B13E2069D6956105BD0E739499BDB&fingerprint=on&op=index and https://keybase.io/pkuczynski.

While these aren't as detailed as https://keybase.io/mpapis, they do seem to suggest that the new key is Piotr Kuczynski's, if that helps you (though obviously only @pkuczynski or @mpapis can confirm this for sure).

**Comment by isikyus** [comment] 2018-12-20 23:54
This is confirmed by https://github.com/rvm/rvm/issues/4518

**Comment by roolo** [comment] 2018-12-21 09:20
It also took me a moment to notice there is different key in the white part and the red part :/

<img width="1406" alt="screenshot 2018-12-21 at 10 19 26" src="https://user-images.githubusercontent.com/173141/50334882-ef59e000-0509-11e9-8c1b-abfd5b142b0f.png">

**Comment by pkuczynski** [comment] 2018-12-22 19:02
Thanks for reporting inconsistency in the documentation. I just run a search across rvm and our website repository and fix all of those. Please check https://github.com/rvm/rvm-site/compare/cc11fa98704282fcc489ebed271ce9bf3d1a3a2c..a2f3213e215a4c915b71bcf5ca5e4104dfbfebc2

**Comment by pkuczynski** [comment] 2018-12-22 19:02
@roolo this difference will be fixed on the next release (most likely next week)

**Closed** 2018-12-22 19:02 UTC

**Comment by pkuczynski** [comment] 2019-01-04 14:20
We just released a new version 1.29.7 fixing this issue.

[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities. Thank you if you already one! 🙏
