### ISSUE TITLE
ruby-2.3.1 fails to install on macos

### ISSUE THREAD

**Issue by pcragone** [rvm/rvm#3976] opened 2017-04-03 17:59 UTC
## Description

Unable to install ruby-2.3.1

## Steps to reproduce

 1. rvm install ruby-2.3.1

## Expected behavior

I expect it to install the ruby

## Actual behavior

```
+__rvm_make:0> make -j 1
+make:20> make -j 1
+make:1> zstyle -t :prezto:module:utility:make color
+make:2> ((  0  ))
+make:5> make -j 1
	CC = gcc
	LD = ld
	LDSHARED = gcc -dynamiclib
	CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens   -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
	CPPFLAGS = -I/Users/pragone/.rvm/usr/include -I/usr/include -I/usr/local/Cellar/libyaml/0.1.7/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin16 -I./include -I.
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/Users/pragone/.rvm/usr/lib -L/usr/lib -L/usr/local/Cellar/libyaml/0.1.7/lib -install_name /Users/pragone/.rvm/rubies/ruby-2.3.1/lib/libruby.2.3.0.dylib -current_version 2.3.0 -compatibility_version 2.3.1  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  
	SOLIBS = -lpthread -lgmp -ldl -lobjc 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
translating probes probes.d
. ./vm_opts.h
compiling main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
compiling miniprelude.c
compiling array.c
compiling bignum.c
compiling class.c
compiling compar.c
compiling complex.c
compiling dir.c
compiling dln_find.c
compiling encoding.c
compiling enum.c
compiling enumerator.c
compiling error.c
compiling eval.c
compiling load.c
compiling proc.c
compiling file.c
compiling gc.c
compiling hash.c
compiling inits.c
compiling io.c
compiling marshal.c
compiling math.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
compiling parse.c
compiling process.c
compiling random.c
compiling range.c
compiling rational.c
compiling re.c
compiling regcomp.c
compiling regenc.c
compiling regerror.c
compiling regexec.c
compiling regparse.c
compiling regsyntax.c
compiling ruby.c
compiling safe.c
compiling signal.c
compiling sprintf.c
compiling st.c
compiling strftime.c
compiling string.c
compiling struct.c
compiling symbol.c
compiling time.c
compiling transcode.c
compiling util.c
compiling variable.c
compiling version.c
compiling compile.c
compiling debug.c
compiling iseq.c
compiling vm.c
compiling vm_dump.c
compiling vm_backtrace.c
compiling vm_trace.c
compiling thread.c
thread.c:1079:27: warning: implicit conversion loses integer precision: 'long' to '__darwin_suseconds_t' (aka 'int') [-Wshorten-64-to-32]
        tp->tv_usec = ts.tv_nsec / 1000;
                    ~ ~~~~~~~~~~~^~~~~~
1 warning generated.
compiling cont.c
compiling enc/ascii.c
compiling enc/us_ascii.c
compiling enc/unicode.c
compiling enc/utf_8.c
compiling enc/trans/newline.c
compiling ./missing/explicit_bzero.c
compiling ./missing/setproctitle.c
compiling dmyenc.c
linking miniruby
config.status: creating ruby-runner.c
generating encdb.h
encdb.h updated
rbconfig.rb updated
generating enc.mk
making srcs under enc
make[1]: Nothing to be done for `srcs'.
generating transdb.h
transdb.h updated
compiling dln.c
compiling localeinit.c
creating verconf.h
verconf.h updated
compiling loadpath.c
compiling prelude.c
linking static-library libruby.2.3.0-static.a
verifying static-library libruby.2.3.0-static.a
linking shared-library libruby.2.3.0.dylib
generating makefile exts.mk
configuring -test-/array/resize
configuring -test-/bignum
configuring -test-/bug-3571
configuring -test-/bug-5832
configuring -test-/bug_reporter
configuring -test-/class
configuring -test-/debug
configuring -test-/dln/empty
configuring -test-/exception
configuring -test-/fatal
configuring -test-/file
configuring -test-/float
configuring -test-/funcall
configuring -test-/gvl/call_without_gvl
configuring -test-/hash
configuring -test-/iseq_load
configuring -test-/iter
configuring -test-/load/dot.dot
configuring -test-/marshal/compat
configuring -test-/marshal/internal_ivar
configuring -test-/marshal/usr
configuring -test-/method
configuring -test-/notimplement
configuring -test-/num2int
configuring -test-/path_to_class
configuring -test-/popen_deadlock
configuring -test-/postponed_job
configuring -test-/printf
configuring -test-/proc
configuring -test-/rational
configuring -test-/recursion
configuring -test-/st/foreach
configuring -test-/st/numhash
configuring -test-/st/update
configuring -test-/string
configuring -test-/struct
configuring -test-/symbol
configuring -test-/time
configuring -test-/tracepoint
configuring -test-/typeddata
configuring -test-/vm
configuring -test-/wait_for_single_fd
configuring bigdecimal
configuring cgi/escape
configuring continuation
configuring coverage
configuring date
configuring dbm
header: ndbm.h
library: libc
configuring digest
configuring digest/bubblebabble
configuring digest/md5
configuring digest/rmd160
configuring digest/sha1
configuring digest/sha2
configuring etc
configuring fcntl
configuring fiber
configuring fiddle
configuring gdbm
configuring io/console
configuring io/nonblock
configuring io/wait
configuring json
configuring json/generator
configuring json/parser
configuring mathn/complex
configuring mathn/rational
configuring nkf
configuring objspace
configuring openssl
configuring pathname
configuring psych
configuring pty
configuring racc/cparse
configuring rbconfig/sizeof
configuring readline
configuring ripper
configuring sdbm
configuring socket
configuring stringio
configuring strscan
configuring syslog
configuring thread
configuring tk
............
check struct members..
check libraries....
Use ActiveTcl libraries (if available).
Search tclConfig.sh and tkConfig.sh....................................
Valid [tclConfig.sh, tkConfig.sh] are found in [["/System/Library/Frameworks/Tcl.framework", "/System/Library/Frameworks/Tk.framework"], ["/usr/lib", "/usr/lib"], ["/System/Library/Frameworks/Tcl.framework/Versions/Current", "/System/Library/Frameworks/Tk.framework/Versions/Current"], ["/System/Library/Frameworks/Tcl.framework/Versions/8.5", "/System/Library/Frameworks/Tk.framework/Versions/8.5"], ["/System/Library/Frameworks/Tcl.framework/Versions/8.4", "/System/Library/Frameworks/Tk.framework/Versions/8.4"]]
Use [tclConfig.sh, tkConfig.sh] == ["/System/Library/Frameworks/Tcl.framework/tclConfig.sh", "/System/Library/Frameworks/Tk.framework/tkConfig.sh"]
Use MacOS X Frameworks.

Find Tcl/Tk libraries. Make tcltklib.so which is required by Ruby/Tk.
configuring tk/tkutil
configuring zlib
compiling resize.c
linking shared-object -test-/array/resize.bundle
compiling big2str.c
compiling bigzero.c
compiling div.c
compiling init.c
compiling intpack.c
compiling mul.c
compiling str2big.c
linking shared-object -test-/bignum.bundle
compiling bug.c
linking shared-object -test-/bug-3571/bug.bundle
compiling bug.c
linking shared-object -test-/bug-5832/bug.bundle
compiling bug_reporter.c
linking shared-object -test-/bug_reporter/bug_reporter.bundle
compiling class2name.c
compiling init.c
linking shared-object -test-/class.bundle
compiling init.c
compiling inspector.c
compiling profile_frames.c
linking shared-object -test-/debug.bundle
compiling empty.c
linking shared-object -test-/dln/empty.bundle
compiling dataerror.c
compiling enc_raise.c
compiling ensured.c
compiling init.c
linking shared-object -test-/exception.bundle
compiling rb_fatal.c
linking shared-object -test-/fatal/rb_fatal.bundle
compiling fs.c
compiling init.c
compiling stat.c
linking shared-object -test-/file.bundle
compiling init.c
compiling nextafter.c
linking shared-object -test-/float.bundle
compiling passing_block.c
linking shared-object -test-/funcall/funcall.bundle
compiling call_without_gvl.c
linking shared-object -test-/gvl/call_without_gvl.bundle
compiling delete.c
compiling init.c
linking shared-object -test-/hash.bundle
compiling iseq_load.c
linking shared-object -test-/iseq_load/iseq_load.bundle
compiling break.c
compiling init.c
compiling yield.c
linking shared-object -test-/iter.bundle
compiling dot.dot.c
linking shared-object -test-/load/dot.dot/dot.dot.bundle
compiling usrcompat.c
linking shared-object -test-/marshal/compat.bundle
compiling internal_ivar.c
linking shared-object -test-/marshal/internal_ivar.bundle
compiling usrmarshal.c
linking shared-object -test-/marshal/usr.bundle
compiling arity.c
compiling init.c
linking shared-object -test-/method.bundle
compiling bug.c
linking shared-object -test-/notimplement.bundle
compiling num2int.c
linking shared-object -test-/num2int/num2int.bundle
compiling path_to_class.c
linking shared-object -test-/path_to_class/path_to_class.bundle
make[2]: Nothing to be done for `all'.
compiling postponed_job.c
linking shared-object -test-/postponed_job.bundle
compiling printf.c
linking shared-object -test-/printf.bundle
compiling init.c
compiling receiver.c
compiling super.c
linking shared-object -test-/proc.bundle
compiling rat.c
linking shared-object -test-/rational.bundle
compiling recursion.c
linking shared-object -test-/recursion.bundle
compiling foreach.c
linking shared-object -test-/st/foreach.bundle
compiling numhash.c
linking shared-object -test-/st/numhash.bundle
compiling update.c
linking shared-object -test-/st/update.bundle
compiling coderange.c
compiling cstr.c
compiling ellipsize.c
compiling enc_associate.c
compiling enc_str_buf_cat.c
compiling fstring.c
compiling init.c
compiling modify.c
compiling nofree.c
compiling normalize.c
compiling qsort.c
compiling set_len.c
linking shared-object -test-/string.bundle
compiling duplicate.c
compiling init.c
compiling member.c
linking shared-object -test-/struct.bundle
compiling init.c
compiling type.c
linking shared-object -test-/symbol.bundle
compiling init.c
compiling new.c
linking shared-object -test-/time.bundle
compiling gc_hook.c
compiling tracepoint.c
linking shared-object -test-/tracepoint.bundle
compiling typeddata.c
linking shared-object -test-/typeddata/typeddata.bundle
compiling at_exit.c
linking shared-object -test-/vm/at_exit.bundle
compiling wait_for_single_fd.c
linking shared-object -test-/wait_for_single_fd/wait_for_single_fd.bundle
compiling bigdecimal.c
linking shared-object bigdecimal.bundle
installing default bigdecimal libraries
compiling escape.c
linking shared-object cgi/escape.bundle
compiling continuation.c
linking shared-object continuation.bundle
compiling coverage.c
linking shared-object coverage.bundle
compiling date_core.c
compiling date_parse.c
compiling date_strftime.c
compiling date_strptime.c
linking shared-object date_core.bundle
installing default date_core libraries
compiling dbm.c
linking shared-object dbm.bundle
compiling digest.c
linking shared-object digest.bundle
installing digest libraries
installing default digest libraries
compiling bubblebabble.c
linking shared-object digest/bubblebabble.bundle
compiling md5init.c
linking shared-object digest/md5.bundle
compiling rmd160init.c
linking shared-object digest/rmd160.bundle
compiling sha1init.c
linking shared-object digest/sha1.bundle
compiling sha2init.c
linking shared-object digest/sha2.bundle
installing default sha2 libraries
generating constant definitions
compiling etc.c
linking shared-object etc.bundle
compiling fcntl.c
linking shared-object fcntl.bundle
compiling fiber.c
linking shared-object fiber.bundle
compiling closure.c
compiling conversions.c
compiling fiddle.c
compiling function.c
compiling handle.c
compiling pointer.c
linking shared-object fiddle.bundle
installing default fiddle libraries
compiling gdbm.c
linking shared-object gdbm.bundle
compiling console.c
linking shared-object io/console.bundle
installing default console libraries
compiling nonblock.c
linking shared-object io/nonblock.bundle
compiling wait.c
linking shared-object io/wait.bundle
installing default libraries
compiling generator.c
linking shared-object json/ext/generator.bundle
compiling parser.c
linking shared-object json/ext/parser.bundle
compiling complex.c
linking shared-object mathn/complex.bundle
compiling rational.c
linking shared-object mathn/rational.bundle
compiling nkf.c
linking shared-object nkf.bundle
installing default nkf libraries
compiling object_tracing.c
compiling objspace.c
compiling objspace_dump.c
linking shared-object objspace.bundle
compiling openssl_missing.c
In file included from openssl_missing.c:21:
./openssl_missing.h:70:6: error: conflicting types for 'HMAC_CTX_copy'
void HMAC_CTX_copy(HMAC_CTX *out, HMAC_CTX *in);
     ^
/usr/local/include/openssl/hmac.h:101:5: note: previous declaration is here
int HMAC_CTX_copy(HMAC_CTX *dctx, HMAC_CTX *sctx);
    ^
In file included from openssl_missing.c:21:
./openssl_missing.h:94:5: error: conflicting types for 'EVP_CIPHER_CTX_copy'
int EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, EVP_CIPHER_CTX *in);
    ^
/usr/local/include/openssl/evp.h:542:5: note: previous declaration is here
int EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in);
    ^
openssl_missing.c:25:1: error: conflicting types for 'HMAC_CTX_copy'
HMAC_CTX_copy(HMAC_CTX *out, HMAC_CTX *in)
^
/usr/local/include/openssl/hmac.h:101:5: note: previous declaration is here
int HMAC_CTX_copy(HMAC_CTX *dctx, HMAC_CTX *sctx);
    ^
openssl_missing.c:120:1: error: conflicting types for 'EVP_CIPHER_CTX_copy'
EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, EVP_CIPHER_CTX *in)
^
/usr/local/include/openssl/evp.h:542:5: note: previous declaration is here
int EVP_CIPHER_CTX_copy(EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in);
    ^
4 errors generated.
make[2]: *** [openssl_missing.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
+__rvm_make:0> return 2
```

## Environment info

```
system:

  system:
    uname:        "Darwin eiger 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/usr/local/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.1 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "51 seconds ago"
    path:         "/Users/pragone/.rvm"
    autolibs:     "[rvm_pkg] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pragone/.rvm/bin:/usr/local/bin:/Users/pragone/lib/connectiq/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mpapis** [comment] 2017-04-08 17:35
does `2.3.3` install?

**Comment by pcragone** [comment] 2017-04-08 18:01
Negative.  Looks like the same error.

**Comment by mpapis** [comment] 2017-04-08 19:38
can I see `which -a openssl` - it is possible it's miss-configuration of openssl - or problems with older version

**Comment by pcragone** [comment] 2017-04-08 19:38
```
$ which -a openssl
/usr/bin/openssl
```

**Comment by pcragone** [comment] 2017-04-08 19:40
(For what it's worth, everyone was working fine for quite sometime, and then something broke at some point with readline.  As a result, I tried reinstalling readline, and somewhere along the process of that, I seem to have broken rvm)

**Comment by mpapis** [comment] 2017-04-08 22:31
one more thing: `rvm autolibs status`

**Comment by pcragone** [comment] 2017-04-08 23:17
```
---
value: status
number: 
runner: 
description: 
```

**Comment by mpapis** [comment] 2017-04-09 09:34
I'm assuming you are using homebrew.

1. Can you show me result of
    ```bash
    brew list -1 | grep openssl
    ```
2. Do you use any other package manager like fink or macports?

3. Did you upgrade your OSX recently?

4. Do you have any special environment flags that could influence compilation? (if not sure please [gist](https://gist.github.com) results of `env|sort`)

5. Could you try uninstalling all openssl from homebrew and running installation via rvm again?

**Comment by pcragone** [comment] 2017-04-09 10:31
1.  Can you show me result of
`brew list -1 | grep openssl`
```
drwxr-xr-x  5 pragone  admin  170 Mar  5 07:51 openssl
drwxr-xr-x  3 pragone  admin  102 Mar  5 07:52 openssl@1.1
```

2.  Do you use any other package manager like fink or macports?
```
No
```

3.  Did you upgrade your OSX recently?
```
No
```

4.  Do you have any special environment flags that could influence compilation? (if not sure please gist results of env|sort)

```
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.TP4BNHIyul/Render
BROWSER=open
COLORFGBG=7;0
EDITOR=nano
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
HOME=/Users/pragone
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t2p0:639A8A6E-2B89-4E17-AD31-1B9080F708B9
LANG=en_US.UTF-8
LESS=-F -g -i -M -R -S -w -X -z-4
LESS_TERMCAP_mb=[01;31m
LESS_TERMCAP_md=[01;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[00;47;30m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[01;32m
LOGNAME=pragone
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43
OLDPWD=/Users/pragone
PAGER=less
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pragone/.rvm/bin:/usr/local/bin:/Users/pragone/lib/connectiq/bin
PWD=/Users/pragone
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.KxeRmYJjOR/Listeners
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.0.15
TERM_SESSION_ID=w0t2p0:639A8A6E-2B89-4E17-AD31-1B9080F708B9
TMPDIR=/var/folders/63/lxg4n46n789b1bys3m71h3zh0000gn/T/
USER=pragone
VISUAL=nano
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
_system_arch=x86_64
_system_name=OSX
_system_type=Darwin
_system_version=10.12
install_flag=1
rvm_alias_expanded=
rvm_bin_flag=
rvm_bin_path=/Users/pragone/.rvm/bin
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_path=/Users/pragone/.rvm
rvm_prefix=/Users/pragone
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_ruby_string=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_version=1.29.1 (master)
rvm_wrapper_name=
```

5.  Could you try uninstalling all openssl from homebrew and running installation via rvm again?
```
$ brew uninstall --ignore-dependencies --force openssl
Uninstalling openssl... (3,386 files, 24.1MB)
```

**Comment by pcragone** [comment] 2017-04-09 10:32
FWIW - it's not the end of the world if this is super broken and it's my fault.  I have a desktop I can get things done on when I need.  (And I should be spending all my time studying anyway - currently in medical school with boards in a month.)

But if I've discovered some kind of bug within RVM, I'm more than happy to keep helping you debug it.

**Comment by mpapis** [comment] 2017-04-09 10:55
It is not a bug in code of RVM, but it's an bug in functionality of RVM :D 

Most likely this problem is not caused by what RVM does, but RVM's ideology is to deliver frictionless ruby installation experience - so you could consider your problem a missing future ;)

In point `5.` did you try installing ruby again with rvm? Did it worked this time? Can I see the new output?

**Comment by pcragone** [comment] 2017-04-09 11:06
Haha alright.  Well I certainly appreciate the help.

Good news / bad news, but I'm thinking you're on to something here:

Good news: `rvm install ruby-2.3.3` worked and successfully installed ruby-2.3.3.

Bad news:
```
$ gem install bundler
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
```

**Comment by mpapis** [comment] 2017-04-09 20:26
@pkuczynski didn't we fight this problem recently?

**Comment by pkuczynski** [comment] 2017-10-28 07:55
This issue should be solved by now. Closing. Please re-open if it still exists.

**Closed** 2017-10-28 07:58 UTC
Labels: duplicate, fixed, platform: osx

**Comment by RubenGram** [comment] 2019-02-18 20:44
`rvm install ruby-2.3.1 --with-openssl-dir=/usr/local/opt/openssl` worked for me. Obtained from https://github.com/rvm/rvm/issues/431#issuecomment-2129783.
I listed openssl's with `brew list -1 | grep openssl`, yielding 2 results: **openssl** and **openssl@1.1**.
From logs, it seems that rvm was trying to use **openssl@1.1** instead of **openssl**. So my guess is that the flag `--with-openssl-dir=/usr/local/opt/openssl` did the job to get the right one. Please correct me if I'm wrong.
