### ISSUE TITLE
Gem wrappers not generating correctly with Ruby 3.0.0

### ISSUE THREAD

**Issue by dorner** [rvm/rvm#5034] opened 2021-01-14 18:42 UTC
## Description

Please see issue #5020. I'm still seeing this issue with the latest RVM (1.29.11). This was happening with Rubygems 3.2.3. Downgrading to 3.1.4 made it work.

```
...
ruby-3.0.0 - #generating default wrappers - please wait
Error running 'run_gem_wrappers regenerate',
please read /Users/daniel.orner/.rvm/log/1610641426_ruby-3.0.0/gemset.wrappers.default.log
```

Log contents:
```
+run_gem_wrappers:2> gem_install gem-wrappers
+gem_install:2> typeset gem_name gem_version version_check
+gem_install:4> gem_version='' 
+gem_install:5> __rvm_parse_gems_args gem-wrappers
+__rvm_parse_gems_args:2> typeset 'gem=gem-wrappers'
+__rvm_parse_gems_args:4> __rvm_string_match gem-wrappers '*.gem$'
+__rvm_string_match:2> typeset _string _search
+__rvm_string_match:3> _string=gem-wrappers 
+__rvm_string_match:4> shift
+__rvm_string_match:5> ((  1  ))
+__rvm_string_match:7> _search='*.gem$' 
+__rvm_string_match:8> _search='*.gem$' 
+__rvm_string_match:9> _search='*.gem$' 
+__rvm_string_match:10> eval '      case "${_string}" in        (*.gem$) return 0 ;;      esac      '
+(eval):1> case gem-wrappers (*.gem\$)
+__rvm_string_match:15> shift
+__rvm_string_match:5> ((  0  ))
+__rvm_string_match:17> return 1
+__rvm_parse_gems_args:9> gem_name=gem-wrappers 
+__rvm_parse_gems_args:10> case gem-wrappers (*--version*)
+__rvm_parse_gems_args:10> case gem-wrappers (*-v*)
+gem_install:7> [[ -z '' ]]
+gem_install:8> __rvm_db gem_gem-wrappers_version gem_version
+__rvm_db:2> typeset value key variable
+__rvm_db:3> key=gem_gem-wrappers_version 
+__rvm_db:4> variable=gem_version 
+__rvm_db:5> value='' 
+__rvm_db:7> [[ -f /Users/daniel.orner/.rvm/user/db ]]
+__rvm_db:8> value=+__rvm_db:8> __rvm_db_ /Users/daniel.orner/.rvm/user/db gem_gem-wrappers_version
+__rvm_db_:2> typeset __db __key __value
+__rvm_db_:3> __db=/Users/daniel.orner/.rvm/user/db 
+__rvm_db_:4> __key=gem_gem-wrappers_version 
+__rvm_db_:5> shift 2
+__rvm_db_:6> __value='' 
+__rvm_db_:7> case  (unset|delete)
+__rvm_db_:7> case  ()
+__rvm_db_:12> __rvm_db_get /Users/daniel.orner/.rvm/user/db gem_gem-wrappers_version
+__rvm_db_get:2> [[ -f /Users/daniel.orner/.rvm/user/db ]]
+__rvm_db_get:3> __rvm_sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+__rvm_sed:0> sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+__rvm_db:8> value='' 
+__rvm_db:10> [[ -z '' && -f /Users/daniel.orner/.rvm/config/db ]]
+__rvm_db:11> value=+__rvm_db:11> __rvm_db_ /Users/daniel.orner/.rvm/config/db gem_gem-wrappers_version
+__rvm_db_:2> typeset __db __key __value
+__rvm_db_:3> __db=/Users/daniel.orner/.rvm/config/db 
+__rvm_db_:4> __key=gem_gem-wrappers_version 
+__rvm_db_:5> shift 2
+__rvm_db_:6> __value='' 
+__rvm_db_:7> case  (unset|delete)
+__rvm_db_:7> case  ()
+__rvm_db_:12> __rvm_db_get /Users/daniel.orner/.rvm/config/db gem_gem-wrappers_version
+__rvm_db_get:2> [[ -f /Users/daniel.orner/.rvm/config/db ]]
+__rvm_db_get:3> __rvm_sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+__rvm_sed:0> sed -n -e '\#^gem_gem-wrappers_version=# { s#^gem_gem-wrappers_version=##;; p; }' -e '/^$/d'
+__rvm_db:11> value='>=1.4.0' 
+__rvm_db:13> [[ -n '>=1.4.0' ]]
+__rvm_db:14> [[ -n gem_version ]]
+__rvm_db:15> eval 'gem_version='\''>=1.4.0'\'
+(eval):1> gem_version='>=1.4.0' 
+__rvm_db:18> true
+gem_install:12> ((  0 == 0  ))
+gem_install:12> is_gem_installed
+is_gem_installed:2> typeset gem_spec
+is_gem_installed:3> gem_spec='gem '\''gem-wrappers'\' 
+is_gem_installed:5> [[ -n '>=1.4.0' ]]
+is_gem_installed:7> gem_spec+=', '\''>=1.4.0'\' 
+is_gem_installed:8> version_check=1.4.0 
+is_gem_installed:13> __rvm_ls -ld /Users/daniel.orner/.rvm/gems/ruby-3.0.0@content_bots/gems/gem-wrappers-1.4.0
+is_gem_installed:14> /Users/daniel.orner/.rvm/rubies/ruby-3.0.0/bin/ruby -rrubygems -e 'gem '\''gem-wrappers'\'', '\''>=1.4.0'\'
+gem_install:14> rvm_log 'gem gem-wrappers >=1.4.0 is already installed'
+rvm_log:2> [[ '' == 1 ]]
+rvm_log:4> printf %b 'gem gem-wrappers >=1.4.0 is already installed\n'
+gem_install:15> return 0
+run_gem_wrappers:3> gem wrappers regenerate
+gem:2> typeset result
+gem:4> typeset rvmrc
+gem:5> rvm_rvmrc_files=( /etc/rvmrc /Users/daniel.orner/.rvmrc ) 
+gem:6> [[ -n /Users/daniel.orner ]]
+gem:6> [[ /Users/daniel.orner/.rvmrc -ef /Users/daniel.orner/.rvmrc ]]
+gem:7> rvm_rvmrc_files+=( /Users/daniel.orner/.rvmrc ) 
+gem:10> rvmrc=/etc/rvmrc
+gem:11> [[ -s /etc/rvmrc ]]
+gem:11> true
+gem:10> rvmrc=/Users/daniel.orner/.rvmrc
+gem:11> [[ -s /Users/daniel.orner/.rvmrc ]]
+gem:11> true
+gem:10> rvmrc=/Users/daniel.orner/.rvmrc
+gem:11> [[ -s /Users/daniel.orner/.rvmrc ]]
+gem:11> true
+gem:13> unset rvm_rvmrc_files
+gem:14> gem wrappers regenerate
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
+gem:15> result=1 
+gem:16> hash -r
+gem:17> return 1
+run_gem_wrappers:4> return 1
```

## Steps to reproduce

I'm on Mac Catalina (10.15.7), RVM 1.29.11, Rubygems 3.2.3

`rvm install 3.0.0`

## Expected behavior

Ruby is installed with gem wrapping as expected

## Actual behavior

See error above.

**Comment by pkuczynski** [comment] 2021-01-14 18:46
@pedrofurtado can you maybe have a look?

**Comment by pedrofurtado** [comment] 2021-01-15 01:37
@pkuczynski I think this bug stills occurs with @dorner because he is using rvm 1.29.11 instead of rvm-master (because the recent bugfixes is in repo, but not in a official release yet)

**Comment by pedrofurtado** [comment] 2021-01-15 01:38
Maybe can be a good time to release v1.29.12, to provide for community in a official release this recent bugfixes of ruby 3 and so on. What do you think about, @pkuczynski ? 🤝

**Comment by pedrofurtado** [comment] 2021-01-15 01:47
A important note: @dorner, after the release of v1.29.12+, if the error still occurs with you, let us know, right? 🤝  Then we will debug together to find the root cause 🔍 

But it is almost confirmed this issue are already fixed in https://github.com/rvm/rvm/pull/5027 | https://github.com/rvm/rvm/pull/5029 | https://github.com/rvm/rvm/pull/5030, with hotfix code inside repo, it is only not released yet.

**Comment by dorner** [comment] 2021-01-15 14:26
Ah, OK! I could have sworn I read somewhere that this was fixed with 1.29.11. Apologies! I'll test again after 12 is released. Thanks very much!

**Comment by pedrofurtado** [comment] 2021-01-15 14:38
@dorner A workaround, for a while, is to get rvm master:

```
curl -ksSL https://get.rvm.io | bash -s -- --branch master
source /etc/profile.d/rvm.sh
```

Let me know if, once downloaded the rvm master, if the error still occurs 🤝

**Comment by pkuczynski** [comment] 2021-01-15 18:36
Indeed! I will release 1.29.12 tonight...

**Closed** 2021-01-15 18:36 UTC
Labels: bug, duplicate

**Comment by dorner** [comment] 2021-01-27 15:09
@pkuczynski confirmed it works! Thanks very much!
