### ISSUE TITLE
OpenSSL Mac OS X Mojave 10.14.6 RVM 2.0.0

### ISSUE THREAD

**Issue by dmunozvenegas** [rvm/rvm#4977] opened 2020-09-11 00:39 UTC
## Description

Installing rvm in mojave when bundling or installing gems I have problems with OpenSSL

## Steps to reproduce

 1. gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \curl -sSL https://get.rvm.io | bash -s stable
 2. rvm install 2.0.0 --rubygems 2.7.8
 3. rvm use 2.0.0
 4. bundle install

## Expected behavior

El comportamiento esperado es instalar rvm 2.0.0 y luego hacer "bundle install" sin inconvenientes.

## Actual behavior

--sudo gem install rails

**message in console**
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources

**Comment by BanzaiMan** [comment] 2020-09-17 16:14
This is basically a duplicate of

#4819
#4781
#4463

**Closed** 2020-10-08 23:19 UTC
Labels: duplicate
