### ISSUE TITLE
BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"

### ISSUE THREAD

**Issue by wanabewired** [rvm/rvm#3872] opened 2017-01-09 11:36 UTC
Hi, i'm trying to update and am receiving the following:

```
$ rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/ubuntu/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed Nov  2 19:59:26 2016 UTC using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/ubuntu/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

-bash: return: _ret: numeric argument required
ubuntu@bwin:~$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
ubuntu@bwin:~$ command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
ubuntu@bwin:~$ rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/ubuntu/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed Nov  2 19:59:26 2016 UTC using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/ubuntu/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

-bash: return: _ret: numeric argument required
```

**Comment by valeriujieanu** [comment] 2017-01-09 12:06
Hello,

The issue is also present on CentOS 7. I just encountered it. Last time I tried on Friday and it worked.

```
root@my-machine: ~ > /usr/local/rvm/bin/rvm get stable && /usr/local/rvm/bin/rvm reload   Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Wed 02 Nov 2016 08:59:26 PM CET using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/usr/local/rvm/scripts/functions/cli: line 246: return: _ret: numeric argument required
root@my-machine: ~ > gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@my-machine: ~ > command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@my-machine: ~ > cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
root@my-machine: ~ >
```

**Comment by GarPit** [comment] 2017-01-09 12:28
+1

**Comment by pkuczynski** [comment] 2017-01-09 12:31
This might be caused by old version of GPG v1 (see #3544). Could you please try getting latest RVM `rvm get master` and let me know if the issue still persist?

**Comment by obfuscoder** [comment] 2017-01-09 12:53
`rvm get master` also fails on my system with same issue:

```
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/klehmann/.rvm/archives/rvm-installer.asc
gpg: Signature made Mi 02 Nov 2016 20:59:26 CET using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/klehmann/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
```

Installing the key with the proposed command does not help.

**Comment by Enucatl** [comment] 2017-01-09 12:53
`rvm get master` returns the same key error for me

**Comment by pkuczynski** [comment] 2017-01-09 13:06
Could you please post your version of gpg?

```
gpg --version
gpg2 --version
```

**Comment by obfuscoder** [comment] 2017-01-09 13:12
```
> gpg --version
gpg (GnuPG) 1.4.20
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

> gpg2 --version
gpg (GnuPG) 2.1.11
libgcrypt 1.6.5
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by pkuczynski** [comment] 2017-01-09 13:15
Have you run `gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`?

**Comment by obfuscoder** [comment] 2017-01-09 13:15
Note that I get this error for whichever version of RVM I try to install. So also this fails:

```
rvm get 1.28.0
rvm get 1.26.0
rvm get 1.25.0
```

**Comment by obfuscoder** [comment] 2017-01-09 13:15
```
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by Enucatl** [comment] 2017-01-09 13:18
`14:16 abis_m@pc9689:~$ gpg --version
gpg (GnuPG) 1.4.16
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg                                                                                                                                    
Supported algorithms:                                                                                                                             
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA                                                                                                             
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,                                                                                
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
14:17 abis_m@pc9689:~$ 
14:17 abis_m@pc9689:~$ 
14:17 abis_m@pc9689:~$ 
14:17 abis_m@pc9689:~$ gpg2 --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ?, ?
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
14:17 abis_m@pc9689:~$ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/abis_m/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed Nov  2 20:59:26 2016 CET using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/abis_m/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.

bash: return: _ret: numeric argument required
14:18 abis_m@pc9689:~$ 



`

**Comment by valeriujieanu** [comment] 2017-01-09 13:47
On my Centos 7 only gpg2 is installed. gpg is a symlink to gpg2.

```
root@my-machine: ~ > gpg --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ?, ?, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
root@my-machine: ~ > gpg2 --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ?, ?, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by henderea** [comment] 2017-01-09 13:56
@pkuczynski did you get an update for the .asc when you updated the rvm-installer script?  I think the issue is that the script changed and no longer matches the signature.  It looks like there was a commit to the script 3 hours ago but the .asc was last updated 2 months ago.

**Comment by henderea** [comment] 2017-01-09 13:58
Looking at the history of the binscripts folder, it looks like we need @mpapis to re-sign the script when he gets a chance.

**Comment by jordiclariana** [comment] 2017-01-09 14:26
Same problem here.
After a lot for test and fail I think that what @henderea says is right. There's no way to make it work and it seems a signature problem.

**Comment by valeriujieanu** [comment] 2017-01-09 14:26
I replaced 
```
/usr/local/rvm/bin/rvm get stable && /usr/local/rvm/bin/rvm reload
```
with 
```
/usr/local/rvm/bin/rvm get 1.28 && /usr/local/rvm/bin/rvm reload
```
and the issue is gone.  I have 1.28 already installed. Maybe it's related to the latest version?

**Comment by jordiclariana** [comment] 2017-01-09 14:29
@valeriujieanu it doesn't work for me. First of all it complains about the version (it has to be something like this: `stable|latest|latest-x.y|x.y.z|head|master|branch|help`

Also, if I try this:
```
~/.rvm/bin/rvm get 1.28.0

Hi there, it looks like you have requested updating rvm to version 1.28.0,
if your intention was ruby installation use instead: rvm install 1.28.0

Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/deploy/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed 02 Nov 2016 08:59:26 PM CET using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/deploy/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/home/deploy/.rvm/scripts/functions/cli: line 246: return: _ret: numeric argument required
```

So the problem persist.

**Comment by obfuscoder** [comment] 2017-01-09 14:32
Is the cause the same as in #3796 ? The script was updated but not resigned after the update?

**Comment by valeriujieanu** [comment] 2017-01-09 14:33
@jordiclariana you are right

```
/usr/local/rvm/bin/rvm get 1.28.0 && /usr/local/rvm/bin/rvm reload   
Hi there, it looks like you have requested updating rvm to version 1.28.0,
if your intention was ruby installation use instead: rvm install 1.28.0

Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Wed 02 Nov 2016 08:59:26 PM CET using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/usr/local/rvm/scripts/functions/cli: line 246: return: _ret: numeric argument required
```

However, editing `rvm1-ansible/defaults/main.yml` like below ran the Ansible role fine.

```
# rvm version to use
#rvm1_rvm_version: 'stable'
rvm1_rvm_version: '1.28'
```

I believe this to be working by mistake.

**Comment by pkuczynski** [comment] 2017-01-09 15:17
This should be fixed now. Please get latest master and try again.

**Closed by pkuczynski** 2017-01-09 15:17 UTC
Labels: feedback needed

**Comment by henderea** [comment] 2017-01-09 15:23
Yep, works for me now.

**Comment by pkuczynski** [comment] 2017-01-09 15:23
Thanks for reporting and testing!

**Comment by OldManCoder** [comment] 2017-03-16 16:15
I'm new to Linux and github and I know this is an old thread but I was able to get it to work by:

_command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import_ 

then 

_curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer | bash -s stable_

Hope that helps someone else who, like me, doesn't really know what they're doing.  ;)

**Comment by pmontrasio** [comment] 2017-03-30 10:40
I'm still stuck with 1.27.0. Unfortunately ```rvm get master``` doesn't work because the tar.gz is damaged

```
$ rvm get master
Downloading https://get.rvm.io

Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc

Verifying /home/me/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 03:05:42 PM CET using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/me/.rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Could not extract RVM sources.
Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Could not extract RVM sources.
Could not update RVM, get some help at #rvm IRC channel at freenode servers.
```

This is confirmed by 

```
$ tar tfz /home/me/.rvm/archives/rvm-master.tgz 
...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by pmontrasio** [comment] 2017-03-30 10:50
Solved: it was because I had this ~/.curlrc

```
-w "\n"
```

Maybe you can call curl with the -q option that prevents it from reading the .curlrc file.

man curl on Ubuntu 16.04

```
-q     If used as the first parameter on the command line, the curlrc config file will not be read and used. See the  -K,  --config  for
       details on the default config file search path.
```

**Comment by medBouzid** [comment] 2017-09-15 20:54
I have debian 9 and I cannot install rvm, I get this error  :  

```
mody@debian:~$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.3.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc
gpg: Signature made Sun 10 Sep 2017 09:59:21 PM WEST
gpg:                using RSA key E206C29FBF04FF17
gpg: lookup_hashtable failed: Unknown system error
gpg: trustdb: searching trust record failed: Unknown system error
gpg: Error: The trustdb is corrupted.
gpg: You may try to re-create the trustdb using the commands:
gpg:   cd ~/.gnupg
gpg:   gpg --export-ownertrust > otrust.tmp
gpg:   rm trustdb.gpg
gpg:   gpg --import-ownertrust < otrust.tmp
gpg: If that does not work, please consult the manual
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/mody/.rvm/archives/rvm-1.29.3.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.

any help??
```

**Comment by ankurjha21** [comment] 2018-01-23 06:04
gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 
try this it works for me

**Comment by ryu1kn** [comment] 2018-03-29 10:37
Thanks @pmontrasio, I had the same problem!!
