### ISSUE TITLE
.github/: Can't update time for .github

### ISSUE THREAD

**Issue by kevdogg** [rvm/rvm#4275] opened 2018-01-04 06:22 UTC
Just installed new rvm, however now when I go to do anything with rvm -- for example

rvm get master

I received the following error:
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying //Users/kevdog/.rvm/archives/rvm-installer.asc
gpg: Signature made Sat Sep  9 14:49:18 2017 EST
gpg:                using RSA key E206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '//Users/kevdog/.rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
.github/: Can't update time for .github
tar: Error exit delayed from previous errors.
Could not extract RVM sources.
Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz
.github/: Can't update time for .github
tar: Error exit delayed from previous errors.
Could not extract RVM sources.
Could not update RVM, please report to https://github.com/rvm/rvm/issues

Why can the time be updated for .github?  I'm confused.  gpg2 is installed.

**Comment by HarryHartmann** [comment] 2018-01-04 12:46
see issue #4274 'Could not update RVM (rvm get master)'; as a workaround you can fix it with:
(1) sudo rm -rf /usr/share/rvm/src/rvm/* /usr/share/rvm/src/rvm/..?* /usr/share/rvm/src/rvm/.[!.]*
then repeat your rvm get master again

**Comment by mpapis** [comment] 2018-01-25 16:00
duplicate of #4274

**Closed by mpapis** 2018-01-25 16:00 UTC
