### ISSUE TITLE
Install tries to update /etc/openssl instead of /usr/local/etc/openssl

### ISSUE THREAD

**Issue by exact** [rvm/rvm#3330] opened 2015-03-03 23:27 UTC
On OS X Yosemite, I have a single-user install, I am not in sudoers and the directory `/etc/openssl` does not exist.

```
~ which rvm
/Users/donncha/.rvm/bin/rvm
~ rvm version
rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
~  rvm install 2.1.5
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.1.5.tar.bz2
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.1.5 - #configure
ruby-2.1.5 - #download
ruby-2.1.5 - #validate archive
ruby-2.1.5 - #extract
ruby-2.1.5 - #validate binary
ruby-2.1.5 - #setup
ruby-2.1.5 - #gemset created /Users/donncha/.rvm/gems/ruby-2.1.5@global
ruby-2.1.5 - #importing gemset /Users/donncha/.rvm/gemsets/global.gems....................................
ruby-2.1.5 - #generating global wrappers........
ruby-2.1.5 - #gemset created /Users/donncha/.rvm/gems/ruby-2.1.5
ruby-2.1.5 - #importing gemsetfile /Users/donncha/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.1.5 - #generating default wrappers........
Updating certificates in '/etc/openssl/cert.pem'.
mkdir: /etc/openssl: Permission denied
mkdir -p "/etc/openssl" failed, retrying with sudo

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

donncha password required for 'mkdir -p /etc/openssl': 
```

In the initial check it correctly determines that the openssl certs are in __/usr/local/etc/openssl/cert.pem__ and that they are up-to-date, but then tries to upgrade non-existent certs in __/etc/openssl__ (which doesn't exist), requiring the use of `sudo`, to which I don't have access.

Two issues:
a) why is it updating certs if it has already determined they're OK, and
b) why isn't it updating the correct cert file

**Comment by exact** [comment] 2015-03-03 23:30
I can workaround this by switching to a user who does have sudo access and running
`sudo rvm osx-ssl-certs update all`, but that shouldn't be necessary.

**Comment by costa** [comment] 2015-03-25 15:16
+1

**Comment by costa** [comment] 2015-04-01 16:34
Moreover, in my case, it asks for the `sudo` password for something, then uses it for something else, look:
```
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.2.1.tar.bz2
Checking requirements for osx.
Updating certificates in '/opt/local/etc/openssl/cert.pem'.
MyUser password required for 'command tee /opt/local/etc/openssl/cert.pem':
Requirements installation successful.
ruby-2.2.1 - #configure
ruby-2.2.1 - #download
######################################################################## 100.0%
ruby-2.2.1 - #validate archive
ruby-2.2.1 - #extract
ruby-2.2.1 - #validate binary
ruby-2.2.1 - #setup
ruby-2.2.1 - #gemset created /Users/kp0t/.rvm/gems/ruby-2.2.1@global
ruby-2.2.1 - #importing gemset /Users/kp0t/.rvm/gemsets/global.gems..............................
ruby-2.2.1 - #generating global wrappers........
ruby-2.2.1 - #gemset created /Users/kp0t/.rvm/gems/ruby-2.2.1
ruby-2.2.1 - #importing gemsetfile /Users/kp0t/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.2.1 - #generating default wrappers........
Updating certificates in '/etc/openssl/cert.pem'.
```
Hello? I didn't give you permission to update my system certificates, now what the F?

**Comment by havenwood** [comment] 2015-04-02 19:01
@exact When `autolibs` are enabled the `/usr/local/etc/openssl` openssl is setup as a requirement for being able to compile dynamically linked Rubies on OS X. If you `rvm install 2.1.5 --disable-binary` and compile you'll notice you won't then see the `/etc/openssl` being setup. The latter is just used for statically linked precompiled binaries like the 2.1.5 OS X binary you're installing.

@costa Hello. Give `man sudo` and `man sudoers` a read, then `man visudo` so you can configure your sudoers file with the settings you prefer. If you set `timestamp_timeout=0` your system will always prompt you for a password instead of waiting x minutes before asking for a password again. This isn't an RVM setting, it's your system.

**Comment by costa** [comment] 2015-04-04 12:10
@havenwood Thanks for the advice, now more importantly, why exactly `rvm install` needed to update `/etc` when I was installing 2.2.1 (and as far as I know it doesn't have those weird statically linked binaries that cannot use openssl's own directory as a base)?

**Comment by havenwood** [comment] 2015-04-04 17:17
@costa [Additional binaries for OS X](https://github.com/wayneeseguin/rvm/pull/335) are now available, including 2.2.1. You can `rvm install 2.2.1 --disable-binary` if you prefer to compile from source.

**Comment by costa** [comment] 2015-04-04 17:54
@havenwood I'm sorry I don't understand how this answers my question.
I did a local install of rvm (without intention of changing anything in my system);
rvm asked a sudo password for /opt/local/etc;
I thought: okay, it's a bit too nice of rvm, but I'll let it change the current openssl's certs (openssl living in /opt/local);
Then it went on and — without any further confirmation — changed a file in an unexpected location (belonging to neither openssl nor rvm installation) for no apparent reason.
So I'm looking for that reason.
I'm kind of experienced rvm user, but this kind of behaviour strikes me for the first time.

**Comment by havenwood** [comment] 2015-04-04 18:29
> as far as I know it doesn't have those weird statically linked binaries

I was just responding to this. You're mistaken. There is a precompiled statically linked binary available for 2.2.1 now! You can see you're using the precompiled binary in the log you posted above but you still have the option to compile from source if you prefer.

> without intention of changing anything in my system

You can set `rvm autolibs read-only` to use available dependencies and ignore missing ones. This will also skip updating openssl certs. There's more information about your options in the [autolibs documentation](https://rvm.io/rvm/autolibs).

> without any further confirmation

Configure your sudoers file with the behavior you prefer. If there are further sudo-related issues please open a new issue.

**Comment by costa** [comment] 2015-04-05 15:40
@havenwood Thank you for your answer.

I hope you don't mind me asking who's responsible for compiling the rubies. I'd like to see the reason behind "linking" `/etc` statically. Clueless that I am might think that there's no problem to statically link an openssl library which knows of the natural location of the cert file.

Now, if `/etc` is what Ruby 2.2.1 needs, who needs `/opt/local/etc`?

**Comment by havenwood** [comment] 2015-04-08 20:41
@costa OS X has deprecated OpenSSL in favor of Common Crypto, so OS X doesn't ship with a version of OpenSSL that modern Ruby can compile against. 

The `/opt/local/etc/openssl` directory on your system was likely created by the [MacPorts](https://www.macports.org/) package manager. As the `/usr/local/etc/openssl` initially reported on this Issue was likely created by the [Homebrew](http://brew.sh/) package manager. Neither of these directories exist on a fresh OS X install.

> Now, if /etc is what Ruby 2.2.1 needs, who needs /opt/local/etc?

The package-manager-provided OpenSSL satisfies the dynamic linking dependency when compiling Ruby 2.2.1. The [SM-Framework](https://smf.sh/)-provided [statically installed](https://github.com/sm/sm-libraries/blob/d04a34d9146ea5482f2286d0b18f77937cbb9f54/openssl/config/defaults#L6) OpenSSL satisfied the static linking dependency for precompiled Ruby 2.2.1. This [article discusses statically linking external dependencies](http://yehudakatz.com/2012/06/05/tokaido-status-update-implementation-details/) with Ruby on OS X. All of the code is open source if you'd like to explore and if you have questions just drop by the [#rvm Freenode IRC channel](https://webchat.freenode.net/?channels=rvm).

**Comment by costa** [comment] 2015-04-13 13:34
@havenwood Thanks again. Now I've tried to look for that statically linked OpenSSL lib you mentioned, but I couldn't find it. Any ideas?

**Comment by toadle** [comment] 2015-04-16 19:57
Guys, I had the same problem and found my solution here. Blogged about it: 
http://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html

**Comment by toadle** [comment] 2015-04-17 07:14
@mpapis Ask to be mentioned here via this tweet :-)!
https://twitter.com/rvm_io/status/588957794713399297

**Comment by postmodem** [comment] 2015-05-22 21:40
@toadle Thanks so much for that blog post. It helped me a resolve the very same issue—one I've been troubleshooting all day.

**Comment by mpapis** [comment] 2015-08-11 11:36
@toadle @postmodem it's not the same issue, your problem was that you had manually installed certificates in a custom path in your system and not installed them in OSX certificate store.

anyway I think both issues could be "fixed" if RVM detected `SSL_CERT_FILE="..."` and did not update the certificates, instead issue a warning about custom path and that it's not being automatically updated.

**Comment by bitaxis** [comment] 2015-08-16 15:34
This came up for me when I started to use a self-signed certificate to secure a single sign-on application.  Not quite sure if an empty, non-existent, nor custom ```SSL_CERT_DIR``` is the root cause, because for me, this was happening both on my Linux host where I deploy my SSO-enabled Rails applications to as well as on my Mac, where I develop and test those applications.  But, contrary to the Mac, the ```SSL_CERT_DIR``` rvm-installed Rubies point to is _not empty_ on my Linux host.

But, Mislav Marohnić's http://mislav.uniqpath.com/2013/07/ruby-openssl/ article and his [ssl-tools](https://github.com/mislav/ssl-tools) repo provided me with the solution/workaround I need.  Basically, I would use ```create-cert``` to create the certificate, run ```sudo c_rehash``` on it, and then move the file and links into ```SSL_CERT_DIR```.

I had to do this on my Linux host as well as copy the certificate to my Mac and do the same so that both the SSO application and others integrated with it are able to pass certificate verification when run from both machines.

My assumption was that if I were to use a purchased certificate, then this would not be a problem.  But thus far, I've not been willing to pony up the money.  😊

**Comment by mpapis** [comment] 2015-08-17 12:34
@bitaxis RVM does not change `SSL_CERT_DIR` environment variable, if you are having problems with it - has to be something else, as for the binaries provided by RVM and the `/etc/openssl/certs` - it's a standard path, no reason to not use it, further more: RVM does update this path with your OSX stores certificates when you install ruby, there is even a command to update all OpenSSL paths that your rubies point to: `rvm osx-ssl-certs update all`

you can still use the certificates generated Mislavs tool by adding them to the OSX certificate store.

**Comment by bitaxis** [comment] 2015-08-20 14:15
@mapis Good to hear that RVM does not change SSL_CERT_DIR environment variable.  Perhaps it is OpenSSL and/or CommonCrypto that is doing it then.

Still loving RVM for all it does.  Please keep up the excellent work!

**Comment by kimardenmiller** [comment] 2015-09-11 17:49
@toadle linked blog worked for me, though things starting working when I ran "brew doctor", which led me to clues like "unset SSL_CERT_DIR"

**Comment by jmyers0022** [comment] 2015-10-01 17:06
@toadle thanks for the blog post. Worked for me as well. :+1:

**Comment by pik** [comment] 2015-10-12 03:56
@mpapis I have updated with that command and still experienced the same problem, so I believe this issue is still unfixed on the RVM side.

**Comment by Vanuan** [comment] 2015-10-15 14:32
I believe, rvm should somehow distinguish between different OS X versions and install corresponding binary.

**Comment by Vanuan** [comment] 2015-10-15 14:36
What's `uname -r` on Yosemite and Maverics?

**Comment by pik** [comment] 2015-10-15 14:59
`14.4.0` for Yosemite.

**Comment by toadle** [comment] 2015-10-15 14:59
`15.0.0` for El Capitan

**Comment by mpapis** [comment] 2015-10-16 18:02
@Vanuan according to apple they have full backwards compatibility, it should be enough to specify flag back to which version you want support and anything upwards should be good. As it looks they do not keep that premise. 

all that apart, the problem here was about RVM using `/etc/openssl` which is part of RVM binaries no difference which version you would use - closing this issue as invalid

finally if there is a bug with `rvm install <ruby-version> --disable-binary` - please open separate issue with the full error and mentioned log files

**Closed by mpapis** 2015-10-16 18:02 UTC

**Comment by pik** [comment] 2015-10-17 00:53
This problem only happens with RVM ruby binaries and there is no working solution listed -- short of building ruby from source - how is this an invalid issue?

**Comment by Vanuan** [comment] 2015-10-17 20:02
Wow.
"We provided compiled binaries for OS X. And it worked well until Apple developers made an incompatible change. Stupid morons they are. We won't provide compiled binaries anymore. So f*ck off."

**Comment by pik** [comment] 2015-10-17 20:16
Compiled binaries that cause issues for most users and don't fix anything aren't of any kind of benefit to those users -- you might see it as unrewarding (free work for github issues) but let's be clear about it when you say you support X with Y: you are wasting every-bodies time with that kind of not-true-to-facts statements. (I've already had a similar problem with fish-shell support: which has a  shim and explicit instructions on the rvm website -- and which do not work and the issue for which was closed 'i.e. we don't support fish-shell - despite the official documentation') 
The fact is that rbenv works, they don't auto-install shitty useless binaries that waste developer time and they don't have a ludicrous 50k+  LoC for a simple program that anyone should be able to patch when they encounter an issue. You want your users to "f*ck off" and good riddance  I say.

**Comment by mpapis** [comment] 2015-10-17 20:28
please do not confuse problems, problem here in this ticket is not actually a bug, Apple does not provide package manager nor openssl, so anyone willing to provide software for OSX needs to statically link against openssl, as a side effect of this - anyone providing software needs to pick a path for the openssl configuration, by default UNIX / Linux uses `/etc` for configuration. so RVM uses it - and this ticket is about it!

if you have problems with anything else please open a separate issue, RVM contributors are here to help and solve the problems.

**Comment by Vanuan** [comment] 2015-10-17 20:38
@mpapis 
So, is it really hard to provide difficult configuration path for different versions of OS X?

**Comment by mpapis** [comment] 2015-10-18 23:17
@Vanuan it is not hard, it is impossible, the one path that is set it is hard coded in the binary, to change it a new binary has to be compiled.

**Comment by Vanuan** [comment] 2015-10-19 00:31
@mpapis so, is it hard to compile a new binary?

**Comment by toadle** [comment] 2015-10-19 07:08
@mpapis Is there a way to install and use `openssl` with decent userbase that uses `/etc/openssl` as their path? Under my impression most people install using `homebrew` which uses `/usr/local/etc/openssl` and therefore is a problem. 

If there is a different way other than `homebrew` which most of users actually use than this is indeed invalid and should be closed. Otherwise I'd suggest to use the PATH with the biggest userbase.

**Comment by mpapis** [comment] 2015-10-20 13:16
From top of my head: `homebrew`, `macports`, `fink`, `sm` (used by RVM to compile the binary rubies). This gives 4 for start, there is more, `homebrew` might be the leading one, but each of them will have a different path ... even better `homebrew` can be installed in different paths, picking just one path is not an option.

As long as Apple does not provide a default package manager for OSX with default paths there is only so much others can do to overcome their mess.

**Comment by toadle** [comment] 2015-10-20 13:30
@mpapis Perhaps a short warning then, when installing a precompiled binary?
So that the obvious solution to the SSL-problem is right there, when not installing from source?

**Comment by pik** [comment] 2015-10-20 13:36
I don't know about others but for me `sudo rvm osx-ssl-certs update all` did not fix anything either.

Imho what really should happen during the binary install procedure is that it should check if ssl certs are present at the expected binary path  -- if not install should end with a warning and give instructions for fixing this or suggest installing with --disable-binary (on a sidenote why does building ruby suddenly require dtrace, are these just the default ./configure settings supplied by rbenv/rvm?).

**Comment by mpapis** [comment] 2015-10-20 14:06
@pik  `rvm osx-ssl-certs update all` does not require `sudo`, also you might be missing point about it, what it does is import certificates from OSX certificates store, which should be ultimate source of certificates on OSX as it's the official place certificates are stored on this system.

**Comment by pik** [comment] 2015-10-20 14:11
I don't know much about the osx ecosystem since I've mostly used linux - all I meant to say is that did not fix ssl errors with rvm for me (where as rbenv's install which builds from source works fine -- I assume rvm would as well with --disable-binary).

**Comment by mpapis** [comment] 2015-10-20 14:19
@pik I would need to know more about your expectations, but yes, the `--disable-binary` would have worked for you most likely.

**Comment by jgerry** [comment] 2015-10-29 15:56
I just ran into this issue with Ruby 2.1.4 using the AWS SDK. Re-installng via ```rvm reinstall 2.1.4 --disable-binary``` almost worked -- I did have to remove my 2.1.4 gemsets and rebuild them first. Now everything seems to be working properly. I suspect had I removed 2.1.4 and its gemsets entirely and re-installed 2.1.4 it would have worked without issue.

**Comment by Cynth42** [comment] 2017-02-07 23:10
I'm trying to update ssl certificate and I'm being asked for password.  Don't know what password they are asking for.  Somebody please help me-thanks
Updating certificates for /etc/openssl/cert.pem: Updating certificates in '/etc/openssl/cert.pem'.
 password required for 'command tee /etc/openssl/cert.pem': 
Sorry, try again.
 password required for 'command tee /etc/openssl/cert.pem':

**Comment by pkuczynski** [comment] 2017-02-07 23:11
It needs `root` password.

**Comment by Cynth42** [comment] 2017-02-07 23:13
it needs root password and i'm not sure what the root password is

**Comment by pkuczynski** [comment] 2017-02-07 23:38
Then it wont work.

**Comment by Cynth42** [comment] 2017-02-07 23:48
Thank you! are there other options?

**Comment by blairanderson** [comment] 2017-03-29 19:27
@Cynth42 password has **nothing** to do with RVM. you should read this: http://askubuntu.com/questions/44418/how-to-enable-root-login
