### ISSUE TITLE
Use `brew list --formula` instead

### ISSUE THREAD

**Issue by berezovskyi** [rvm/rvm#5017] opened 2020-12-25 11:25 UTC
## Description

Brew warns that the deprecated command invocation has now been disabled:

> Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.

## Steps to reproduce

 1. Install and load RVM version 1.29.10
 2. Install Homebrew 2.7.0
 3. Run `rvm upgrade 2.7`

## Expected behavior

No errors from brew are returned. But other than that, I don't think it impacts RVM because brew lists all formulae and casks.

## Actual behavior

* [command](https://gist.github.com/berezovskyi/bfe38dd0ea3aa104d34cf953ea66586f)

## Environment info

<details>
<summary>Details</summary>

ruby-2.6.3:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin driib-KTH.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"
    zsh:          "/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        ""

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "5 minutes 36 seconds ago"
    path:         "/Users/andrew/.rvm"
    autolibs:     "[enable] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.3p62"
    date:         "2019-04-16"
    platform:     "x86_64-darwin18"
    patchlevel:   "2019-04-16 revision 67580"
    full_version: "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]"

  homes:
    gem:          "/Users/andrew/.rvm/gems/ruby-2.6.3"
    ruby:         "/Users/andrew/.rvm/rubies/ruby-2.6.3"

  binaries:
    ruby:         "/Users/andrew/.rvm/rubies/ruby-2.6.3/bin/ruby"
    irb:          "/Users/andrew/.rvm/gems/ruby-2.6.3/bin/irb"
    gem:          "/Users/andrew/.rvm/rubies/ruby-2.6.3/bin/gem"
    rake:         "/Users/andrew/.rvm/gems/ruby-2.6.3/bin/rake"

  environment:
    PATH:         "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/andrew/.rvm/gems/ruby-2.6.3/bin:/Users/andrew/.rvm/gems/ruby-2.6.3@global/bin:/Users/andrew/.rvm/rubies/ruby-2.6.3/bin:/usr/local/opt/node@12/bin:/usr/local/sbin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/andrew/.jenv/shims:/usr/local/opt/gnupg@1.4/libexec/gpgbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Library/TeX/texbin:/Users/andrew/go/bin:/Users/andrew/.rvm/bin:/Users/andrew/google-cloud-sdk/path.zsh.inc:/Users/andrew/opt/apache-jena/bin:/usr/local/Cellar/node/15.2.0/bin:/usr/local/opt/fzf/bin:/Users/andrew/.rvm/bin"
    GEM_HOME:     "/Users/andrew/.rvm/gems/ruby-2.6.3"
    GEM_PATH:     "/Users/andrew/.rvm/gems/ruby-2.6.3:/Users/andrew/.rvm/gems/ruby-2.6.3@global"
    MY_RUBY_HOME: "/Users/andrew/.rvm/rubies/ruby-2.6.3"
    IRBRC:        "/Users/andrew/.rvm/rubies/ruby-2.6.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

</details>

**Comment by ruurd** [comment] 2020-12-25 16:02
Can you close this, it is a duplicate of #4998

**Comment by berezovskyi** [comment] 2020-12-25 16:06
I think that ticket mixes up two problems: a 404 issue and this warning which does not break anything (as you can see from my log). I think that ticket should focus on the ruby install (as https://github.com/rvm/rvm/issues/4998#issuecomment-726518548 points out, the installation should proceed with the build from source). But I am totally fine if maintainers decide otherwise.

**Comment by bvicenzo** [comment] 2020-12-25 17:45
It seems that it was reported here https://github.com/rvm/rvm/issues/5007 and fixed here https://github.com/rvm/rvm/pull/4995.

**Closed** 2020-12-25 17:50 UTC
