### ISSUE TITLE
Incorrect installation on Ubuntu 16.10

### ISSUE THREAD

**Issue by slavafomin** [rvm/rvm#3840] opened 2016-12-15 11:53 UTC
Hello! Thank you for this program!

However,

## Description

After **rvm** is installed on my **Xubuntu 16.10 x64** machine, it's not loaded with the shell automatically. I have to manually run `source /home/slava/.rvm/scripts/rvm` or to add `[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.` to the `~/.bashrc` file.

Here's my `~/.profile` after installation:

```
$ cat ~/.profile 
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

Here's my `~/.bashrc` after installation:

```
$ cat ~/.bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export NVM_DIR="/home/slava/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
```

## Steps to reproduce

 1. Install rvm with ruby (`--ruby`) on Xubuntu 16.10 x64 using default installation instructions
 2. Try to use `rvm` or `ruby`
 3. Bash will fail to find them

## Expected behavior

Both executables should work out of the box by default.

## Environment info

```
$ rvm info

ruby-2.3.0:

  system:
    uname:       "Linux intrepid 4.8.0-30-generic #32-Ubuntu SMP Fri Dec 2 03:43:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "ubuntu/16.10/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "13 minutes 16 seconds ago"
    path:         "/home/slava/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.3.0p0"
    date:         "2015-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2015-12-25 revision 53290"
    full_version: "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]"

  homes:
    gem:          "/home/slava/.rvm/gems/ruby-2.3.0"
    ruby:         "/home/slava/.rvm/rubies/ruby-2.3.0"

  binaries:
    ruby:         "/home/slava/.rvm/rubies/ruby-2.3.0/bin/ruby"
    irb:          "/home/slava/.rvm/rubies/ruby-2.3.0/bin/irb"
    gem:          "/home/slava/.rvm/rubies/ruby-2.3.0/bin/gem"
    rake:         "/home/slava/.rvm/rubies/ruby-2.3.0/bin/rake"

  environment:
    PATH:         "/home/slava/.rvm/gems/ruby-2.3.0/bin:/home/slava/.rvm/gems/ruby-2.3.0@global/bin:/home/slava/.rvm/rubies/ruby-2.3.0/bin:/home/slava/.nvm/versions/node/v7.2.1/bin:/home/slava/bin:/home/slava/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/slava/.rvm/bin"
    GEM_HOME:     "/home/slava/.rvm/gems/ruby-2.3.0"
    GEM_PATH:     "/home/slava/.rvm/gems/ruby-2.3.0:/home/slava/.rvm/gems/ruby-2.3.0@global"
    MY_RUBY_HOME: "/home/slava/.rvm/rubies/ruby-2.3.0"
    IRBRC:        "/home/slava/.rvm/rubies/ruby-2.3.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mpapis** [comment] 2017-02-12 17:26
did you check <http://rvm.io/integration/gnome-terminal>?

**Comment by danielpclark** [comment] 2017-02-19 23:12
I can confirm this issue.  In Ubuntu 14 using the gnome terminal as a login shell worked fine.  But ~~upgrading~~ reinstalling to Ubuntu 16.10 the gnome terminal, and the other terminals, all seem to fail to act like a login shell.  Probably a bash issue.

I tried what I could with the instructions online.  I've even reinstalled RVM to `/usr/share` and tried hardcoding some paths.  _I think I may have been able to get RVM to work poorly by hand, but I'm not sure._

What's solved the situation for me is I've switched over to FishShell.

**Comment by raelgc** [comment] 2017-02-20 16:47
@danielpclark, can you, please, try the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by danielpclark** [comment] 2017-02-20 17:56
@raelgc I have already tried that.  I see that repository in my `apt/sources.list.d/rael-gc-ubuntu-rvm-yakkety.list`.  I can't remember whether this is how I ended up with `rvm` in my `/usr/share` or not since it's been a while.

It would be a lot of work for me to try and revert my shell and experiment with rvm's install again.  Anyone can replicate this issue simply using VirtualBox with Ubuntu 16.10 (64bit) image.  Sorry, this would require more time than I'm willing to give on this issue.

**Comment by raelgc** [comment] 2017-02-20 18:09
@danhealy Yes, the Ubuntu package installs RVM to `/usr/share`. You check if, after the upgrade, the option to run terminal as login shell is still checked like described in the step 2 of the package repo?

**Comment by danielpclark** [comment] 2017-02-20 18:28
Yes, that command is checked.  I keep it that way.  That doesn't work.

**Comment by mpapis** [comment] 2017-02-20 21:43
can you try specifying shell: `/bin/bash --login`?

**Comment by danielpclark** [comment] 2017-02-21 00:24
If I remember that correctly that would work (because I have tried that).  At the moment I don't have access to bash as a shell directly anymore. _(bash command reloads my fishshell - probably a fishshell feature)_

**Comment by mpapis** [comment] 2017-02-23 10:16
@danielpclark the PATH issue is a separate thing and it is about your shell initialization files changing PATH to:
1. include ruby before sourcing rvm
2. changing it after rvm was sourced

have you tried `\curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles`?

**Comment by mpapis** [comment] 2017-09-17 11:47
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Closed by mpapis** 2017-09-17 11:47 UTC
Labels: feedback needed
