### ISSUE TITLE
RVM suggesting to `rvm use rvm`

### ISSUE THREAD

**Issue by kronn** [rvm/rvm#3268] opened 2015-01-16 10:46 UTC
When cd'ing into a project directory, I get the following warning:

```
Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rvm'.
```

however:

`$GEM_HOME` and `$PATH` are set sensibly (before and after cd).

A solution is to remove the `.rvmrc` from the directory, leaving only `.ruby-version` and `.ruby-gemset`.

Our `.rvmrc` reads the `.ruby-version` and `.ruby-gemset` and also adds some shell aliases and functions related to the project:

```
rvm $(cat .ruby-version)@$(cat .ruby-gemset) --create

# useful aliases may be added here
alias cu='truncate --size 0 log/*.log; clear; zeus cucumber -r features/'
```

Of course, `rvm use rvm` does neither make sense nor work. Well, at least until there is a ruby called "rvm", which will break a lot things anyway :smile: 

What are we doing wrong?

**Comment by mpapis** [comment] 2015-01-16 10:49
can you also show the `PATH`, `GEM_PATH` and `GEM_HOME` before + after the call?

**Comment by kronn** [comment] 2015-01-16 12:58
before:

```
PATH
/usr/local/rvm/gems/ruby-1.9.3-p194/bin:/usr/local/rvm/gems/ruby-1.9.3-p194@global/bin:/usr/local/rvm/rubies/ruby-1.9.3-p194/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
local/rvm/bin
GEM_PATH
/usr/local/rvm/gems/ruby-1.9.3-p194:/usr/local/rvm/gems/ruby-1.9.3-p194@global
GEM_HOME
/usr/local/rvm/gems/ruby-1.9.3-p194
```

after

```
PATH
/usr/local/rvm/gems/ruby-2.1.4@gemset_name/bin:/usr/local/rvm/gems/ruby-2.1.4@global/bin:/usr/local/rvm/rubies/ruby-2.1.4/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
GEM_PATH
/usr/local/rvm/gems/ruby-2.1.4@gemset_name:/usr/local/rvm/gems/ruby-2.1.4@global
GEM_HOME
/usr/local/rvm/gems/ruby-2.1.4@gemset_name
```

the complete log from the console is gisted here: https://gist.github.com/kronn/6b4585ed0ded9db77a9c

RVM is now at version 1.26.9, we did not have the warning with rvm 1.25.5.

**Comment by jowl** [comment] 2015-01-19 08:49
I'm also experiencing something similar to this, and investigated a bit further. I set `rvm_trace_flag=1` and sourced `.rvmrc` without errors, I then opened a new shell from within the project directory, and got errors. Below are the relevant (anonymized) section of the traces.

Sourcing `.rvmrc`:
```
$ grep GEM_HOME source-rvmrc.log
+ 9:33:17 /Users/$USER/.rvm/scripts/functions/selector:10 __rvm_select_set_variable_defaults:2 export GEM_HOME GEM_PATH MY_RUBY_HOME RUBY_VERSION IRBRC
+ 9:33:17 /Users/$USER/.rvm/scripts/functions/selector:181 __rvm_use_:22 export GEM_HOME GEM_PATH MY_RUBY_HOME RUBY_VERSION IRBRC
+ 9:33:17 /Users/$USER/.rvm/scripts/functions/selector:182 __rvm_use_:23 GEM_HOME=/Users/$USER/.rvm/gems/jruby-1.7.2@my-gemset
```

Opening a new shell:
```
$ grep GEM_HOME new-shell.log
+ 9:31:00 /Users/$USER/.rvm/environments/default:2 /Users/$USER/.rvm/environments/default:2 export 'GEM_HOME=/Users/$USER/.rvm/gems/ruby-2.0.0-p247'
+ 9:31:00 /Users/$USER/.rvm/scripts/functions/rvmrc_project:80 __rvm_load_project_config:19 case thenunset GEM_HOME GEM_PATH
+ 9:31:00 /Users/$USER/.rvm/scripts/functions/cli:29 __rvm_path_match_gem_home_check_warning_missing:2 rvm_warn 'Warning! PATH is not properly set up, $GEM_HOME is not set,
+ 9:31:00 /Users/$USER/.rvm/scripts/functions/logging:138 rvm_warn:3 thenprintf %b 'Warning! PATH is not properly set up, $GEM_HOME is not set,
Warning! PATH is not properly set up, $GEM_HOME is not set,
+ 9:31:00 /Users/$USER/.rvm/scripts/functions/selector:10 __rvm_select_set_variable_defaults:2 export GEM_HOME GEM_PATH MY_RUBY_HOME RUBY_VERSION IRBRC
+ 9:31:01 /Users/$USER/.rvm/scripts/functions/selector:181 __rvm_use_:22 export GEM_HOME GEM_PATH MY_RUBY_HOME RUBY_VERSION IRBRC
+ 9:31:01 /Users/$USER/.rvm/scripts/functions/selector:182 __rvm_use_:23 GEM_HOME=/Users/$USER/.rvm/gems/jruby-1.7.2@my-gemset
```

As you can see, the `$GEM_HOME` variable is unset on `~/.rvm/scripts/functions/rvmrc_project:80` when opening a new shell, but not when simply sourcing `.rvmrc`. It seems as if the check occurs too soon in the former case, since a proper `$GEM_HOME` is set after the warning has been issued.

@kronn To temporarily disable the warning, you can do `export rvm_silence_path_mismatch_check_flag=1`. This doesn't fix anything, but simply hides the warning.

I'd be happy to provide you with more information, please just ask if you need anything else.

**Comment by Fudoshiki** [comment] 2015-04-16 11:29
I have this issue too
rvm 1.26.11

**Comment by justin808** [comment] 2015-07-04 22:56
This is a valid issue that I see when I run `rvm info` right after opening a terminal window to a directory with a .ruby-version and .ruby-gemset. 

When I open a new shell, I can run:
```
rvm info
```
and see the issue...

```
> rvm info                                                                                                                                                                                        [12:53:45]
Warning! PATH is not properly set up, '/Users/justin/.rvm/gems/ruby-2.2.1@rails42/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.1@rails42'.
```

and then I can run this:
```
cd .. && cd -
```

and that fixes the issue (can run `rvm info` with no warning)

**Comment by mpapis** [comment] 2015-07-04 23:15
@justin808 RVM will not use your ruby from `.ruby-version` when your shell initialization files taint the environment already, you need to fix your shell initialization files as it is described in the message

**Comment by justin808** [comment] 2015-07-04 23:15
@mpapis Any idea on the heroku issue?

**Comment by havenwood** [comment] 2015-08-20 22:58
Closing as a duplicate of #3038 (some solutions are discussed there).

**Closed by havenwood** 2015-08-20 22:58 UTC
Labels: feedback needed

**Comment by kronn** [comment] 2015-08-23 10:04
hmm, we are not using heroku toolbelt, this happens on our production machines. It happens consistently for rake-tasks that are executed with `/bin/bash -l -c 'cd /path/to/app && bundle exec bin/

**Also, while I can work around the warning, I still see the suggestion of executing `rvm use rvm`.**

As this is not considered an issue (and it's not related to heroku toolbelt), what am I doing wrong?
