### ISSUE TITLE
Can't download Ruby 3.0.0-preview2

### ISSUE THREAD

**Issue by Souravgoswami** [rvm/rvm#5014] opened 2020-12-19 17:24 UTC
## Description

Ruby 3.0.0-preview2 was released around 9 days ago which doesn't offer the bz2 file:

![image](https://user-images.githubusercontent.com/37468605/102695345-b1087000-424c-11eb-962b-0e8779a4d995.png)

So when I am trying to install Ruby 3.0.0-preview2, it gives me the following error:

```
$ CC=clang HOSTCC=clang CFLAGS="-O3 -march=native -mtune=native -fno-plt" rvm install ruby-3.0.0-preview2
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.32/x86_64/ruby-3.0.0-preview2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Requirements installation successful.
Installing Ruby from source to: /home/sourav/.rvm/rubies/ruby-3.0.0-preview2, this may take a while depending on your cpu(s)...
ruby-3.0.0-preview2 - #downloading ruby-3.0.0-preview2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
The requested url does not exist(22): 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0-preview2.tar.bz2'
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0-preview2.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```

## Steps to reproduce

Try installing ruby-3.0.0-preview2

## Expected behavior
It should get ruby-3.0.0-preview2 and I should be able to give it the extension as well.

## Info

Running `rvm info` gives:

```
$ rvm info

ruby-2.7.1:

  system:
    uname:        "Linux archlinux 5.9.9-xanmod1-1 #1 SMP PREEMPT Fri, 20 Nov 2020 07:44:55 +0000 x86_64 GNU/Linux"
    name:         "Arch"
    version:      "libc-2.32"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.1.0(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.8 (x86_64-pc-linux-gnu)"
    remote_path:  "arch/libc-2.32/x86_64"

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "23 minutes 58 seconds ago"
    path:         "/home/sourav/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.7.2p137"
    date:         "2020-10-01"
    platform:     "x86_64-linux"
    patchlevel:   "2020-10-01 revision 5445e04352"
    full_version: "ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]"

  homes:
    gem:          "/home/sourav/.rvm/gems/ruby-2.7.1"
    ruby:         "/home/sourav/.rvm/rubies/ruby-2.7.1"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/home/sourav/.rvm/gems/ruby-2.7.1/bin:/home/sourav/.rvm/gems/ruby-2.7.1@global/bin:/home/sourav/.rvm/rubies/ruby-2.7.1/bin:/opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64:/opt/intel/compilers_and_libraries_2020.2.254/linux/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/intel/bin:/opt/intel/inspector_2020.2.0.604588/bin64:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sourav/.rvm/bin:/home/sourav/.gem/ruby/2.7.0/bin"
    GEM_HOME:     "/home/sourav/.rvm/gems/ruby-2.7.1"
    GEM_PATH:     "/home/sourav/.rvm/gems/ruby-2.7.1:/home/sourav/.rvm/gems/ruby-2.7.1@global"
    MY_RUBY_HOME: "/home/sourav/.rvm/rubies/ruby-2.7.1"
    IRBRC:        "/home/sourav/.rvm/rubies/ruby-2.7.1/.irbrc"
    RUBYOPT:      "-W0"
    gemset:       ""
```

**Comment by jasnow** [comment] 2020-12-19 17:33
Maybe adding the output of "rvm info" would be helpful.

**Comment by jasnow** [comment] 2020-12-19 18:03
Root cause: Appears bz2 version of (cached/tarred) ruby-3.0.0-preview2 is missing.

**Comment by Souravgoswami** [comment] 2020-12-19 18:05
Thanks @jasnow, I was managed to download Ruby 3.0.0 Preview 2 zip file locally, unzip it, made it tar.bz2, and install it:

```
wget -O ruby-3.0.0-preview2.zip https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0-preview2.zip && unzip ruby-3.0.0-preview2 && tar -cvjSf ruby-3.0.0-preview2.bz2 ruby-3.0.0-preview2/ && cp ruby-3.0.0-preview2.tar.bz2 ~/.rvm/archives/ CC=clang HOSTCC=clang CFLAGS="-O3 -march=native -mtune=native -fno-plt" rvm install --verify-downloads 2 ruby-3.0.0-preview2
```

**Comment by jasnow** [comment] 2020-12-20 17:58
ruby-3.0.0.rc1 too:
```
The requested url does not exist(22): 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0-rc1.tar.bz2'
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.0/ruby-3.0-rc1.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.```

**Comment by pcarn** [comment] 2020-12-20 19:57
I made a change to RVM to use .tar.gz for ruby 3, since they're not publishing .tar.bz2 anymore:
https://github.com/rvm/rvm/commit/a244d19978b6720d7713dc13d273ab357363b62f

@Souravgoswami @jasnow Have you tried `rvm get head` to pull the latest, and try installing again?

**Comment by jasnow** [comment] 2020-12-20 20:10
* Ran "rvm get head" then "rvm install "ruby-3.0-preview2" and got:
 ```
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-3.0-preview2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/USER/.rvm/rubies/ruby-3.0-preview2, this may take a while depending on your cpu(s)...
ruby-3.0-preview2 - #downloading ruby-3.0-preview2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0-preview2.tar.bz2'
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.0/ruby-3.0-preview2.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```

**Comment by pcarn** [comment] 2020-12-20 20:17
@jasnow Try `rvm install ruby-3.0.0-preview2`.

The ruby version has `3.0.0` in it, see https://cache.ruby-lang.org/pub/ruby/3.0/

**Comment by jasnow** [comment] 2020-12-20 20:26
Running "rvm install ruby-3.0.0-preview2" as suggest above gets:
```
ruby-3.0.0-preview2 - #removing src/ruby-3.0.0-preview2..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-3.0.0-preview2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/USER/.rvm/rubies/ruby-3.0.0-preview2, this may take a while depending on your cpu(s)...
ruby-3.0.0-preview2 - #downloading ruby-3.0.0-preview2, this may take a while depending on your connection...
ruby-3.0.0-preview2 - #extracting ruby-3.0.0-preview2 to /Users/USER/.rvm/src/ruby-3.0.0-preview2.....
ruby-3.0.0-preview2 - #configuring..
Error running 'env CFLAGS=-O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include LDFLAGS=-L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib ./configure --prefix=/Users/USER/.rvm/rubies/ruby-3.0.0-preview2 --disable-install-doc --enable-shared',
please read /Users/USER/.rvm/log/1608495638_ruby-3.0.0-preview2/configure.log
There has been an error while running configure. Halting the installation.
```
and configure.log is:
```
[2020-12-20 15:21:44] ./configure
current path: /Users/USER/.rvm/src/ruby-3.0.0-preview2
PATH=/Users/USER/.rvm/usr/bin:/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/USER/.rvm/gems/ruby-2.7.2@ruby2.7-rails6.2/bin:/Users/USER/.rvm/gems/ruby-2.7.2@global/bin:/Users/USER/.rvm/rubies/ruby-2.7.2/bin:/Users/USER/.asdf/shims:/Users/USER/.asdf/bin:/Users/USER/.rbenv/shims:/usr/local/sbin:/Users/USER/bin/binutils:/usr/local/opt/git/bin:/usr/local/heroku/bin:/Users/USER/bin:/usr/local/phantomjs-1.9.0-linux-i686/bin:/Users/USER/rbx-dev/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/bin/data-science-at-the-command-line/tools:/Users/USER/Projects/gocode/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/USER/bin/sorbet:/Users/USER/.rvm/bin
command(7): env CFLAGS=-O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include LDFLAGS=-L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib ./configure --prefix=/Users/USER/.rvm/rubies/ruby-3.0.0-preview2 --disable-install-doc --enable-shared
checking for ruby... /Users/USER/.rvm/rubies/ruby-2.7.2/bin/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... i386-apple-darwin16.7.0
checking host system type... i386-apple-darwin16.7.0
checking target system type... i386-apple-darwin16.7.0
checking for /usr/local/Cellar/ld/10.2.0/bin/gcc-8... no
checking for /usr/local/Cellar/gcc-ar/10.2.0/bin/gcc-8... no
checking for /usr/local/Cellar/g++/10.2.0/bin/gcc-8... no
checking for /usr/local/Cellar/gcc-nm/10.2.0/bin/gcc-8... no
checking for /usr/local/Cellar/gcc-ranlib/10.2.0/bin/gcc-8... no
checking for gcc... /usr/local/Cellar/gcc/10.2.0/bin/gcc-8
checking whether the C compiler works... no
configure: error: in `/Users/USER/.rvm/src/ruby-3.0.0-preview2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by pkuczynski** [comment] 2020-12-20 21:08
I am closing this, as the download works now.

**Closed by pkuczynski** 2020-12-20 21:08 UTC

**Comment by pedrofurtado** [comment] 2020-12-25 13:55
@pkuczynski  Trying to install ruby 3.0.0. official release with rvm 1.29.10, and not works, because rvm try to download bz2 file (that not exists). Is there any planning to release rvm 1.29.11?

**Comment by pkuczynski** [comment] 2020-12-25 14:06
Try rvm get master

**Comment by pedrofurtado** [comment] 2020-12-25 14:13
Yes! rvm get head works well here, but it is better a official release asap (after Christmas, of course 🎅 ) 🤝

**Comment by pkuczynski** [comment] 2020-12-25 14:40
Yeah, I will do that next week :)

**Comment by pedrofurtado** [comment] 2020-12-25 15:10
Thanks a lot! Merry Christmas for all 👍 🤝

**Comment by stochastic-thread** [comment] 2020-12-29 07:49
also, this worked for me:
[rvm upgrade ruby-head ruby-3](url)

**Comment by pedrofurtado** [comment] 2020-12-29 10:54
@stochastic-thread Thanks for feedback! 👋 

Could you provide more details about this workaround? Do you execute `rvm upgrade ruby-head ruby-3` after `rvm install 3.0.0`?

**Comment by pkuczynski** [comment] 2020-12-29 11:21
`rvm get master` should help...

**Comment by sekrett** [comment] 2021-09-17 12:49
Does not work: `rvm get master` and `rvm install ruby-3.0.2`. Tried also stable, head, ruby-3.0.0.
