### ISSUE TITLE
rvm get stable

### ISSUE THREAD

**Issue by peddinti** [rvm/rvm#3466] opened 2015-07-16 08:38 UTC
Hi i am trying to use rvm get stable on server and it is throwing the following error and despite search i am not able to find a fix.

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    459      0 --:--:-- --:--:-- --:--:--   654
100 22721  100 22721    0     0  51564      0 --:--:-- --:--:-- --:--:-- 51564
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
gpg: Signature made Mon 30 Mar 2015 09:52:13 PM UTC using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/ubuntu/.rvm/archives/rvm-1.26.11.tgz' - 'https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

Could not update RVM, get some help at #rvm IRC channel at freenode servers

**Comment by topher6345** [comment] 2015-07-23 18:45
\+ 1 

I'm also having this problem 

```
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 13 Apr 2015 05:05:41 PM MST using RSA key ID BF04FF17
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    sudo gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

/usr/local/rvm/scripts/functions/cli: line 216: return: _ret: numeric argument required
```

running either 

`sudo gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3`

` command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -`

results in the same error

**Comment by havenwood** [comment] 2015-08-11 15:59
Closing as a duplicate of #3110. It's not recommended to install RVM as root. If the suggestions in #3110 or installing as a non-root user don't resolve this problem please open a new Issue.

**Closed by havenwood** 2015-08-11 15:59 UTC
