### ISSUE TITLE
Does not add to $PATH after source ~/.zprofile

### ISSUE THREAD

**Issue by roadhump** [rvm/rvm#3416] opened 2015-05-08 08:39 UTC
I've got my `.zprofile` with something like

```
export PATH=/bin

export PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
```

When I open shell first time 

```
echo $PATH
/Users/roadhump/.rvm/gems/ruby-2.2.0/bin:/bin:/Users/roadhump/.rvm/bin # correct paths of ruby
```

Then I do `source ~/.zprofile` and

```
echo $PATH
/bin:/Users/roadhump/.rvm/bin # without ruby path
```

I'm pretty sure rvm should re-append $PATH here

**Comment by karldotm** [comment] 2015-05-08 21:59
The .zprofile is not the one being utilized when you log in.

The .zprofile wipes out the PATH first - the two lines rvm adds to the .zprofile are only to put the rvm scripts in the PATH and source in the rvm functions.

**Comment by roadhump** [comment] 2015-05-08 22:23
So I suppose I should use `rvm reload` after `source`, is it right?

**Comment by karldotm** [comment] 2015-05-08 22:27
The problem isn't with rvm - in fact in this case rvm and anything in /bin are the only things that will work. Many of what rvm needs to work, including rvm reload, is in /usr/bin and other locations.

I am not sure why someone set up your .zprofile like that but it is not set up like that by rvm or anything other than human intervention that I have ever seen.

**Comment by roadhump** [comment] 2015-05-08 22:33
I put /bin just for example, there is plenty of other paths there of course.

**Comment by havenwood** [comment] 2015-08-24 15:59
Show your full `.zprofile`?

I do suspect that something RVM needs is missing after you nuke and rebuild `PATH`. Try with a `PATH` identical to the original in your `.zprofile`? What has to go missing for it to stop prepending?

**Comment by mpapis** [comment] 2017-09-17 11:53
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Closed by mpapis** 2017-09-17 11:53 UTC
Labels: feedback needed
