### ISSUE TITLE
RVM does not investigate CWD for desired ruby version when bash is spawned

### ISSUE THREAD

**Issue by RST-J** [rvm/rvm#3357] opened 2015-03-25 09:26 UTC
I recently ran into the issue that RVM told me, I had the wrong ruby version selected after we upgraded ruby in our project but I didn't make that version my new default.

Steps to reproduce (using Konsole, probably any terminal):
1. Create project with Gemfile and set some ruby version, e.g. ``ruby '2.2.0'``
2. Set some other ruby version as default, e.g. ``rvm use 2.1.3 --default``
3. Navigate to project directory (RVM will select ruby 2.2.0 as expected)
4. Spawn a new terminal tab (Konsole: Ctrl+Shift+T) and ask ``ruby -v`` which will be 2.1.3

If I leave and reenter the directory, RVM will select the correct ruby version.
Is this intended behavior and if so, may I suggest to change that?

A workaround here is to set the version used in the project as default, but I think it would be better if RVM also checks for which version to select on shell start (think of projects using older rubies).

**Comment by ihinojal** [comment] 2015-04-04 08:11
I have the same problem. Spawning a terminal using `Ctrl+Shift+N` or a new tab using `Ctrl+Shift+T` doesnt pick up the gemset or ruby version from the files `~/.ruby-version` `~/.ruby-gemset`.

I had to manually type `cd .` so rvm picks up the correct ruby version

A workaround is downgrade rvm to `1.25.14` using:

     $ rvm get 1.25.14`

There should be a bug introduced in version 1.25.15 that is causing this problem..

**Comment by d4rky-pl** [comment] 2015-04-24 18:56
Could not reproduce on `rvm 1.26.11 (master)`, could you please make sure this problem still exist?

**Comment by ihinojal** [comment] 2015-04-24 21:23
Yep, it's still present. Maybe only happens on linux machines. For me it happens using *Console Terminal*. To reproduce it:
```
ivan@z11:~/Development/ $ rvm version
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ivan@z11:~/Development/ $ rvm list

rvm rubies

=* jruby-1.7.19 [ x86_64 ]
   ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

ivan@z11:~/Development/ $ cd my_ruby22_project
ivan@z11:~/Development/my_ruby22_project $ cat .ruby-version
ruby-2.2.0
ivan@z11:~/Development/my_ruby22_project $ rvm list 

rvm rubies

 * jruby-1.7.19 [ x86_64 ]
=> ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```
But now if I spawn a new terminal using `Ctrl+Shift+N` or a new tab using `Ctrl+Shift+T`
```
ivan@z11:~/Development/my_ruby22_project $ rvm list

rvm rubies

=* jruby-1.7.19 [ x86_64 ]
   ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```
It defaults to the default ruby version, when I would expect to still had the ruby-2.2.0 version as specified in `.ruby-version`

If still you can't reproduce it, just let me know and I would try in another ubuntu machine. Just to double check

**Comment by d4rky-pl** [comment] 2015-04-24 22:24
This works properly on OS X, I'll make a VM with Ubuntu tomorrow but if you could double check, that'd be nice

**Comment by ihinojal** [comment] 2015-04-25 11:45
I'm having troubles reproducing it in my other machine. So I'm going to investigate more what's causing it. Don't bother right now making a virtual machine because by default it's going to work properly. Wait a while I come with news.

**Comment by ihinojal** [comment] 2015-04-25 12:17
For users having this problem one solution is just to just `rm ~/.rvm` and reinstall rvm..

I moved my `~/.rvm` folder to `~/.rvm.bak` and I reinstalled from scratch rvm (creating a new `~/.rvm` folder). Now it's working fine. I don't known what happened to my old rvm installation..

For me you can mark this as solved. If you want to further investigate what was wrong with my `.rvm` folder I can send you its contents. But probably there will be plenty of better things to work on.. So as you wish :)

**Comment by mpapis** [comment] 2015-04-27 10:50
Closing - we got started on RVM2 so it will be better to focus our efforts there => https://github.com/rvm/rvm2_02#readme

**Closed by mpapis** 2015-04-27 10:50 UTC
