### ISSUE TITLE
Cannot load such file -- zlib

### ISSUE THREAD

**Issue by TrevorHinesley** [rvm/rvm#3389] opened 2015-04-22 06:13 UTC
Using rvm 1.26.11

After installing ruby 2.2.2 or 2.1.6 with RVM on OS X 10.10, I'm getting this error:

```
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

I have tried `rvm pkg install zlib` (I know that's outdated) but that doesn't solve the problem.

Also, doesn't work if I do `rvm get head` with ruby-2.2.2 or ruby-2.1.6 installed anywhere, same error:

```
rvm get head
Downloading https://get.rvm.io
No GPG software exists to validate rvm-installer, skipping.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /Users/Trevor/.rvm/
    RVM PATH line found in /Users/Trevor/.profile /Users/Trevor/.bashrc /Users/Trevor/.zshrc.
    RVM sourcing line found in /Users/Trevor/.bash_profile /Users/Trevor/.zlogin.
    Installing rvm gem in 1 gemsetsError running 'command gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/Trevor/.rvm/log/1429684264_ruby-2.2.2/gem.install.rvm->=1.11.3.9.log
[2015-04-22 01:31:04] command
current path: /Users/Trevor/.rvm/src/rvm
GEM_HOME=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global/bin:/Users/Trevor/.rvm/rubies/ruby-2.2.2/bin:/Users/Trevor/.rvm/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
GEM_PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
command(7): command gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Installing gem-wrappers gem in 1 gemsetsError running 'command gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/Trevor/.rvm/log/1429684265_ruby-2.2.2/gem.install.gem-wrappers->=1.2.7.log
[2015-04-22 01:31:05] command
current path: /Users/Trevor/.rvm/src/rvm
GEM_HOME=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global/bin:/Users/Trevor/.rvm/rubies/ruby-2.2.2/bin:/Users/Trevor/.rvm/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
GEM_PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
command(7): command gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Regenerating gem wrappers in 1 rubiesERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
.
Upgrade of RVM in /Users/Trevor/.rvm/ is complete.

# Trevor Hinesley,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/Trevor/.bash_profile':

      source ~/.profile

  * No new notes to display.

RVM reloaded!
```

**Comment by TrevorHinesley** [comment] 2015-04-22 06:32
Also, doesn't work if I do `rvm get head`, same error:

```
rvm get head
Downloading https://get.rvm.io
No GPG software exists to validate rvm-installer, skipping.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /Users/Trevor/.rvm/
    RVM PATH line found in /Users/Trevor/.profile /Users/Trevor/.bashrc /Users/Trevor/.zshrc.
    RVM sourcing line found in /Users/Trevor/.bash_profile /Users/Trevor/.zlogin.
    Installing rvm gem in 1 gemsetsError running 'command gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/Trevor/.rvm/log/1429684264_ruby-2.2.2/gem.install.rvm->=1.11.3.9.log
[2015-04-22 01:31:04] command
current path: /Users/Trevor/.rvm/src/rvm
GEM_HOME=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global/bin:/Users/Trevor/.rvm/rubies/ruby-2.2.2/bin:/Users/Trevor/.rvm/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
GEM_PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
command(7): command gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/Trevor/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Installing gem-wrappers gem in 1 gemsetsError running 'command gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/Trevor/.rvm/log/1429684265_ruby-2.2.2/gem.install.gem-wrappers->=1.2.7.log
[2015-04-22 01:31:05] command
current path: /Users/Trevor/.rvm/src/rvm
GEM_HOME=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global/bin:/Users/Trevor/.rvm/rubies/ruby-2.2.2/bin:/Users/Trevor/.rvm/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
GEM_PATH=/Users/Trevor/.rvm/gems/ruby-2.2.2@global
command(7): command gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/Trevor/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Regenerating gem wrappers in 1 rubiesERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
.
Upgrade of RVM in /Users/Trevor/.rvm/ is complete.

# Trevor Hinesley,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/Trevor/.bash_profile':

      source ~/.profile

  * No new notes to display.

RVM reloaded!
```

**Comment by TrevorHinesley** [comment] 2015-04-22 07:33
A workaround seems to be installing zlib 1.2.8 using brew.

`brew install zlib`

Then installing 2.1.6 or 2.2.2 with the `--with-zlib-dir` flag, like so:

`rvm install 2.2.2 --with-zlib-dir=/usr/local/Cellar/zlib/1.2.8`

This shouldn't need to be the case though. This is the kind of thing that needs to be done for 1.9.3-p551 (aka versions that are lifed out).

**Comment by d4rky-pl** [comment] 2015-04-28 07:50
I couldn't reproduce this issue on my local machine, but the errors you get are very peculiar. Could you please make sure your local rvm installation is not broken? Please move .rvm to _rvm for a moment, reinstall rvm and see if you can install 2.2.2 correctly.

**Comment by Javix** [comment] 2016-10-31 22:02
It worked for me on a fresh macOS, just with `2.3.0`ruby version:
```

rvm install 2.3.0 --with-zlib-dir=/usr/local/Cellar/zlib/1.2.8
````
Thank you so much @TrevorHinesley.

**Comment by pkuczynski** [comment] 2016-11-01 10:06
@Javix I prepared a patch which requires zlib for home brew. Would you mind testing it on your local?

```
rvm get branch /bugfix/issue-3389
rvm remove 2.3.0
rvm install 2.3.0
```

**Comment by Javix** [comment] 2016-11-01 18:43
@pkuczynski Hello, should I remove RVM that I installed before or I can replay the above patch just on the already installed RVM ?

**Comment by pkuczynski** [comment] 2016-11-01 19:33
`rvm get` would replace your current RVM version with the branched one - created to test the fix. So all you have to do is to run those commands. You might want to uninstall `zlib` from brew, so we can test if it will be installed by RVM.

Thanks in advance for help with testing this issue.

**Comment by Javix** [comment] 2016-11-01 19:42
Ruby `2.3.0` was installed without problem and there were a line saying that `zlib` was being installed. I quitted the terminal, came back and tried to check if it works:
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
➜  ~ gem install bundler
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```
It fails :(

**Comment by pkuczynski** [comment] 2016-11-01 20:29
When you installed ruby, was it installing already pre-build package or compiling from source?

**Comment by Javix** [comment] 2016-11-01 20:38
You can find the full stack trace of the installation in the [gist](https://gist.github.com/Javix/ba24d0016583aa5d700ba27eebe3488b) I created.

**Comment by pkuczynski** [comment] 2016-11-01 20:53
Can you also gist make.log for this particular build?

**Comment by Javix** [comment] 2016-11-01 20:55
Sorry, I can't find `make.log` anywhere, any tips ?

**Comment by Javix** [comment] 2016-11-01 21:30
Here is the latest make.log [gist](https://gist.github.com/Javix/74f24b00092c6f6ba8a5e7b4ce8a8cde)

**Comment by pkuczynski** [comment] 2016-11-01 22:05
Can you try running `xcode-select --install`

**Comment by Javix** [comment] 2016-11-02 09:09
I got the following error when running the command you asked:
````➜  ~ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
````

**Comment by pkuczynski** [comment] 2016-11-02 18:07
Can you list `brew list`

**Comment by Javix** [comment] 2016-11-02 20:30
Here it is:
````
 ~ brew list
autoconf	imagemagick	libksba		libtool		mysql		pkg-config	xz
automake	jpeg		libpng		libyaml		node		readline	zlib
freetype	libgpg-error	libtiff		maven		openssl		wget
```

**Comment by pkuczynski** [comment] 2016-11-02 20:32
`ls -al /usr/include/zlib.h`

**Comment by Javix** [comment] 2016-11-02 20:33
`-rw-r--r--  1 root  wheel  89381 Jul 30 22:58 /usr/include/zlib.h`

**Comment by pkuczynski** [comment] 2016-11-02 20:38
Can you try:

```
brew untap homebrew/dupes
brew tap homebrew/dupes
brew remove zlib
brew install zlib
rvm get master
```

Open new terminal and try to install ruby again.

**Comment by Javix** [comment] 2016-11-02 21:08
It fails [differently](https://gist.github.com/Javix/312485a28d4dd5cf24e3442537bb08bb).

**Comment by mpapis** [comment] 2016-11-02 22:19
could you try:
```bash
rvm remove ruby-2.3.1
rvm remove ruby-2.3.0
rvm install ruby-2.3.1
rvm install ruby-2.3.0
```
the last number in ruby version is a patch number, it does not change behavior in any way and it might include fixes - does 2.3.1 work?

**Comment by Javix** [comment] 2016-11-03 08:37
@mpapis I'll try it later in the evening because of some ports which are blocked:
```
lang.org port 443: Connection refused
There was an error(7).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```

**Comment by Javix** [comment] 2016-11-03 21:06
Nope, still the same error:
```
rvm list

rvm rubies

=* ruby-2.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

~ gem install bundler
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```
Unfortunately, I have no more time to remove and reinstall my ruby with the installed gems every time.

**Closed** 2016-12-07 10:57 UTC
Labels: feedback needed, platform: osx

**Comment by pkuczynski** [comment] 2016-12-07 11:01
I added zlib dependency for macOS and Homebrew. It's not entirely clear if that fully solves this issues so in case of troubles, feel free to open a new issue and reference this one.
