### ISSUE TITLE
libyaml-dev error PCLinuxOS

### ISSUE THREAD

**Issue by VandeK** [rvm/rvm#3709] opened 2016-07-01 19:05 UTC
Hi there, 
I'm totally new to development and struggling trying to install Ruby and Rails on PCLinuxOS.
I've read similar issues were submitted, but as I'm not sure if they were solved or abandoned I'm submitting this one.

Thank you in advance.

The problem is the same, the name of library libyaml-dev is lib64yaml-dev in PCLinuxOS and I could not find a workaround. Here is the output:

rvm 1.27.0 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]
Searching for binary rubies, this might take some time.
No binary rubies available for: pclinuxos/2016/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for pclinuxos.
Installing requirements for pclinuxos.
Updating system..........
Error running 'requirements_pclinuxos_update_system ruby-2.3.0',
showing last 15 lines of /home/username/.rvm/log/1467399207_ruby-2.3.0/update_system.log
++ /scripts/functions/requirements/pclinuxos : requirements_pclinuxos_update_system_check_epel()  58 > [[ -z '' ]]
++ /scripts/functions/requirements/pclinuxos : requirements_pclinuxos_update_system_check_epel()  61 > rvm_error 'There is no '\''libyaml-devel'\'' package available for installation and RVM does not know how to make that happen,
please tell us how to install '\''libyaml-devel'\'' on '\''PCLinuxOS-2016'\'' here: https://github.com/rvm/rvm/issues'
++ /scripts/functions/logging : rvm_error()  115 > rvm_pretty_print stderr
++ /scripts/functions/logging : rvm_pretty_print()  73 > case "${rvm_pretty_print_flag:=auto}" in
++ /scripts/functions/logging : rvm_pretty_print()  78 > case "${TERM:-dumb}" in
++ /scripts/functions/logging : rvm_pretty_print()  81 > case "$1" in
++ /scripts/functions/logging : rvm_pretty_print()  83 > [[ -t 2 ]]
++ /scripts/functions/logging : rvm_pretty_print()  83 > return 1
++ /scripts/functions/logging : rvm_error()  117 > printf %b 'There is no '\''libyaml-devel'\'' package available for installation and RVM does not know how to make that happen,
please tell us how to install '\''libyaml-devel'\'' on '\''PCLinuxOS-2016'\'' here: https://github.com/rvm/rvm/issues\n'
There is no 'libyaml-devel' package available for installation and RVM does not know how to make that happen,
please tell us how to install 'libyaml-devel' on 'PCLinuxOS-2016' here: https://github.com/rvm/rvm/issues
++ /scripts/functions/requirements/pclinuxos : requirements_pclinuxos_update_system_check_epel()  62 > return 49
++ /scripts/functions/requirements/pclinuxos : requirements_pclinuxos_update_system()  73 > return 49
Requirements installation failed with status: 49.

**Comment by pkuczynski** [comment] 2016-11-30 00:47
Duplicate of #3703

**Closed by pkuczynski** 2016-11-30 00:47 UTC
