### ISSUE TITLE
Rubinius Ubuntu dependency clang

### ISSUE THREAD

**Issue by rtrv** [rvm/rvm#4212] opened 2017-10-27 16:57 UTC
On Ubuntu 17.04 there is no clang-3.5, available is 3.7+

Both `rvm install rbx` and `rvm install rbx-2.1.1` fail. RVM version is 1.29.2

Thanks.

**Comment by CpuID** [comment] 2018-03-12 22:26
+1

**Comment by CpuID** [comment] 2018-03-12 22:27
`rvm install rbx-3.100` on Ubuntu 17.10 - logs:

```
++ sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install clang-3.5 llvm-3.5 llvm-3.5-dev libedit-dev'\'': ' apt-get --no-install-recommends --yes install clang-3.5 llvm-3.5 llvm-3.5-dev libedit-dev
Reading package lists...
Building dependency tree...
Reading state information...
Package clang-3.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  clang-5.0:i386 clang-4.0:i386 clang-3.9:i386 clang-3.8:i386 clang:i386
  clang-5.0 clang-4.0 clang-3.9 clang-3.8 clang

E: Package 'clang-3.5' has no installation candidate
E: Unable to locate package llvm-3.5
E: Couldn't find any package by glob 'llvm-3.5'
E: Couldn't find any package by regex 'llvm-3.5'
E: Unable to locate package llvm-3.5-dev
E: Couldn't find any package by glob 'llvm-3.5-dev'
E: Couldn't find any package by regex 'llvm-3.5-dev'
++ return 100
++ return 100
```

**Comment by pkuczynski** [comment] 2018-03-13 00:28
@rtrv and @CpuID could you please try to run:

```
rvm get branch /rbx-ubuntu-17
rvm install rbx-3
```

Your issue should be fixed then

**Comment by CpuID** [comment] 2018-03-13 00:48
@pkuczynski thx for the suggestion, tested it, no dice:

```
$ rvm install rbx-3.100
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/17.10/x86_64/rbx-3.100.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
user password required for 'apt-get --quiet --yes update': Updating system..-
..
Installing required packages: libedit-dev, clang-3.7, llvm-3.7, llvm-3.7-dev.....
Error running 'requirements_debian_libs_install libedit-dev clang-3.7 llvm-3.7 llvm-3.7-dev',
please read /home/user/.rvm/log/1520901982_rbx-3.100/package_install_libedit-dev_clang-3.7_llvm-3.7_llvm-3.7-dev.log
Requirements installation failed with status: 100.
$ rvm version
rvm 1.29.3 (rbx-ubuntu-17) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ tail -n 20 /home/user/.rvm/log/1520901982_rbx-3.100/package_install_libedit-dev_clang-3.7_llvm-3.7_llvm-3.7-dev.log
++ command sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install libedit-dev clang-3.7 llvm-3.7 llvm-3.7-dev'\'': ' apt-get --no-install-recommends --yes install libedit-dev clang-3.7 llvm-3.7 llvm-3.7-dev
++ sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install libedit-dev clang-3.7 llvm-3.7 llvm-3.7-dev'\'': ' apt-get --no-install-recommends --yes install libedit-dev clang-3.7 llvm-3.7 llvm-3.7-dev
Reading package lists...
Building dependency tree...
Reading state information...
Package llvm-3.7 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package clang-3.7 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'clang-3.7' has no installation candidate
E: Package 'llvm-3.7' has no installation candidate
E: Unable to locate package llvm-3.7-dev
E: Couldn't find any package by glob 'llvm-3.7-dev'
E: Couldn't find any package by regex 'llvm-3.7-dev'
++ return 100
++ return 100
```

Same result for `rbx-3` vs `rbx-3.100`.

Note `rvm install rbx-3` hangs for a pretty extended period of time for whatever reason. The above was a lot quicker. Before the `Searching for binary rubies, this might take some timeout.` output.

**Comment by pkuczynski** [comment] 2018-03-13 00:52
Ah in the first report I read that clang-3.7 is available. Could u please retry with:

```
rvm get branch /rbx-ubuntu-17
rvm install rbx-3
```

**Comment by CpuID** [comment] 2018-03-13 01:06
`rvm install rbx-3` still took forever to get to even the first step (some large recursive search going on behind the scenes?), but `rvm install rbx-3.100` is a step closer. Next error:

```
rbx-3.100 - #extracting rubinius-3.100 to /usr/share/rvm/src/rbx-3.100.....
rbx-3.100 - #configuring..
Error running 'env /home/nathan/.rvm/wrappers/ruby-2.5.0@rubinius/ruby ./configure --prefix=/usr/share/rvm/rubies/rbx-3.100 --cc=clang --cxx=clang++',
please read /home/nathan/.rvm/log/1520903047_rbx-3.100/configure.log
 [nathan@ns-desktop-ub ~]$ cat /home/nathan/.rvm/log/1520903047_rbx-3.100/configure.log
[2018-03-13 11:05:26] env
current path: /usr/share/rvm/src/rbx-3.100
PATH=/usr/share/rvm/bin:/home/nathan/git/stackexchange-blackbox/bin:/home/nathan/go/bin:/usr/local/go/bin:/home/nathan/.nvm/versions/node/v8.9.4/bin:/home/nathan/git/stackexchange-blackbox/bin:/home/nathan/go/bin:/usr/local/go/bin:/home/nathan/.rvm/gems/ruby-2.4.1/bin:/home/nathan/.rvm/gems/ruby-2.4.1@global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/nathan/vault:/home/nathan/packer:/home/nathan/terraform:/home/nathan/git/tedconf/infrastructure/bin:/home/nathan/vault:/home/nathan/packer:/home/nathan/terraform
command(6): env /home/nathan/.rvm/wrappers/ruby-2.5.0@rubinius/ruby ./configure --prefix=/usr/share/rvm/rubies/rbx-3.100 --cc=clang --cxx=clang++
------------------------------ Deprecation notice ------------------------------


'configure' is deprecated and will be removed in the future.
Use 'build.sh' to configure, build, package, and install Rubinius.


--------------------------------------------------------------------------------
Checking clang:./configure:1524:in ``': No such file or directory - clang (Errno::ENOENT)
	from ./configure:1524:in `check_tool_version'
	from ./configure:708:in `check_tools'
	from ./configure:1971:in `run'
	from ./configure:2214:in `<main>'
```

**Comment by CpuID** [comment] 2018-03-13 01:06
```
[nathan@ns-desktop-ub ~]$ clang<tab>
clang-3.8                     clang-apply-replacements-3.8  clang-cl-3.8                  clang-rename-3.8              
clang++-3.8                   clang-check-3.8               clang-query-3.8               clang-tblgen-3.8
```

**Comment by CpuID** [comment] 2018-03-13 02:34
Quick (but not ideal) workaround to get it to `configure` on that branch (a few required binaries look versioned):

```
cd /usr/bin
sudo ln -sf clang-3.8 clang
sudo ln -sf clang++-3.8 clang++
```

But then the build fails with:

```
.....
** Invoke machine/class/jit.hpp (not_needed)
** Invoke machine/class/code_db.hpp (not_needed)
** Invoke machine/class/diagnostics.hpp (not_needed)
** Invoke machine/class/trie.hpp (not_needed)
** Invoke machine/class/unwind_site.hpp (not_needed)
** Invoke machine/class/prediction.hpp (not_needed)
** Invoke build/scripts/field_extract.rb (not_needed)
** Invoke run_field_extract 
** Execute machine/invoke_resolver.hpp
** Execute machine/vm
1: LB build/libraries/double-conversion
clang++  -Wall -g -O2 -c src/bignum-dtoa.cc -o src/bignum-dtoa.o
In file included from src/bignum-dtoa.cc:28:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/math.h:36:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cmath:47:
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:101:3: error: unknown type name '__float128'
  __float128
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:7: error: unknown type name '__float128'
  abs(__float128 __x)
      ^
2 errors generated.
Makefile:17: recipe for target 'src/bignum-dtoa.o' failed
make: *** [src/bignum-dtoa.o] Error 1
rake aborted!
Error compiling
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:69:in `command'
(eval):138:in `block (3 levels) in load'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:620:in `block in build'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:619:in `chdir'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:619:in `build'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:940:in `block in linear_tasks'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:939:in `each'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:939:in `linear_tasks'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:933:in `start'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:1060:in `block in build'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:1051:in `each'
/usr/share/rvm/src/rbx-3.100/build/scripts/daedalus.rb:1051:in `build'
/usr/share/rvm/src/rbx-3.100/rakelib/vm.rake:216:in `block in <top (required)>'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/home/nathan/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/share/rvm/rubies/ruby-2.5.0/bin/rake:23:in `load'
/usr/share/rvm/rubies/ruby-2.5.0/bin/rake:23:in `<main>'
/home/nathan/.rvm/gems/ruby-2.5.0@rubinius/bin/ruby_executable_hooks:15:in `eval'
/home/nathan/.rvm/gems/ruby-2.5.0@rubinius/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => install => build:build => machine/vm
Error: make
```

**Comment by pkuczynski** [comment] 2018-03-13 13:29
Could u please remove the links you created, uninstall `clang-3.8`, `llvm-3.8` and `llvm-3.8-dev`, and then give it another try:

```
rvm get branch /rbx-ubuntu-17
rvm install rbx-3
```

**Comment by CpuID** [comment] 2018-03-13 16:59
No dice:

```
[nathan@ns-desktop-ub ~]$ rvm install rbx-3
rbx-3.100 - #removing src/rbx-3.100..
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/17.10/x86_64/rbx-3.100.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system..nathan password required for 'apt-get --quiet --yes update': 
....
Installing required packages: flex, ruby-dev, libreadline-devlibedit-dev, clang-4.0, llvm-4.0, llvm-4.0-dev...
Error running 'requirements_debian_libs_install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev',
please read /home/nathan/.rvm/log/1520960275_rbx-3.100/package_install_flex_ruby-dev_libreadline-devlibedit-dev_clang-4.0_llvm-4.0_llvm-4.0-dev.log
Requirements installation failed with status: 100.
 [nathan@ns-desktop-ub ~]$ cat /home/nathan/.rvm/log/1520960275_rbx-3.100/package_install_flex_ruby-dev_libreadline-devlibedit-dev_clang-4.0_llvm-4.0_llvm-4.0-dev.log
.......
++ __rvm_sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev'\'': ' apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev
++ command sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev'\'': ' apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev
++ sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev'\'': ' apt-get --no-install-recommends --yes install flex ruby-dev libreadline-devlibedit-dev clang-4.0 llvm-4.0 llvm-4.0-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libreadline-devlibedit-dev
++ return 100
++ return 100
 [nathan@ns-desktop-ub ~]$
```

Looks like a side issue to the clang version now :) Appreciate your assistance getting this over the line, happy to keep testing until we get it right.

**Comment by pkuczynski** [comment] 2018-03-13 21:34
My bad! Just pushed a fixed. Could u please try again?

**Comment by CpuID** [comment] 2018-03-13 22:34
Done. Step by step... :) Looks like the `llvm-config` path needs fixing up, I believe `clang` came first before and that didn't error so thats positive:

```
[nathan@ns-desktop-ub ~]$ rvm install rbx-3.100
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/17.10/x86_64/rbx-3.100.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system..nathan password required for 'apt-get --quiet --yes update': 
....
Installing required packages: flex, ruby-dev, clang-4.0, llvm-4.0, llvm-4.0-dev..............
Requirements installation successful.
ruby-2.5.0@rubinius - #regenerating binstubs..........
rbx-3.100 - #downloading rubinius-3.100, this may take a while depending on your connection...
rbx-3.100 - #extracting rubinius-3.100 to /usr/share/rvm/src/rbx-3.100.....
rbx-3.100 - #configuring..
Error running 'env CXXFLAGS=-nostdinc++ -I/usr/include/c++/v1 LDFLAGS=-stdlib=libc++ -lc++ /home/nathan/.rvm/wrappers/ruby-2.5.0@rubinius/ruby ./configure --prefix=/usr/share/rvm/rubies/rbx-3.100 --cc=clang-4.0 --cxx=clang++-4.0 --llvm-config=llvm-config-4.0',
please read /home/nathan/.rvm/log/1520980310_rbx-3.100/configure.log
 [nathan@ns-desktop-ub ~]$ cat /home/nathan/.rvm/log/1520980310_rbx-3.100/configure.log
[2018-03-14 08:32:53] env
current path: /usr/share/rvm/src/rbx-3.100
PATH=/usr/share/rvm/bin:/home/nathan/git/stackexchange-blackbox/bin:/home/nathan/go/bin:/usr/local/go/bin:/home/nathan/.nvm/versions/node/v8.9.4/bin:/home/nathan/git/stackexchange-blackbox/bin:/home/nathan/go/bin:/usr/local/go/bin:/home/nathan/.rvm/gems/ruby-2.4.1/bin:/home/nathan/.rvm/gems/ruby-2.4.1@global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/nathan/vault:/home/nathan/packer:/home/nathan/terraform:/home/nathan/git/tedconf/infrastructure/bin:/home/nathan/vault:/home/nathan/packer:/home/nathan/terraform
command(9): env CXXFLAGS=-nostdinc++ -I/usr/include/c++/v1 LDFLAGS=-stdlib=libc++ -lc++ /home/nathan/.rvm/wrappers/ruby-2.5.0@rubinius/ruby ./configure --prefix=/usr/share/rvm/rubies/rbx-3.100 --cc=clang-4.0 --cxx=clang++-4.0 --llvm-config=llvm-config-4.0
------------------------------ Deprecation notice ------------------------------


'configure' is deprecated and will be removed in the future.
Use 'build.sh' to configure, build, package, and install Rubinius.


--------------------------------------------------------------------------------
Checking clang-4.0: found
Checking clang++-4.0: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': found! (version 4.0.1 - api: 400)

Checking sizeof(short): ./configure:864:in `check_program': Compiling configure test program failed. (RuntimeError)
	from ./configure:908:in `detect_sizeof'
	from ./configure:1458:in `process'
	from ./configure:1976:in `run'
	from ./configure:2214:in `<main>'
```

**Comment by CpuID** [comment] 2018-03-13 23:40
Turns out the last error is not `llvm-config` related, is actually related to a missing LLVM C++ library. Hiding in the `configure.log`:

```
[2018-03-14 09:30:48] clang++-4.0   -nostdinc++ -I/usr/include/c++/v1 -stdlib=libc++ -lc++ -o rbx-configure-test rbx-configure-test.cpp  -fPIC -std=c++11  -Wl,--export-dynamic -lrt -lcrypt -ldl -lpthread -lm  >>/usr/share/rvm/src/rbx-3.100/configure.log 2>&1
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2018-03-14 09:30:48] Compiling configure test program failed.
```

Got past it with:

```
sudo apt-get install libc++-dev libc++abi-dev
```

`configure` now succeeds, and it gets a good portion through the build. The next issue:

```
Running 354 tasks using 3 parallel threads
2: CXX machine/arguments.cpp
3: CXX machine/bytecode_verifier.cpp
4: CXX machine/accessor_primitives.cpp
In file included from machine/arguments.cpp:1:
In file included from /usr/share/rvm/src/rbx-3.100/machine/arguments.hpp:5:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/array.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/object_utils.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/object.hpp:7:
In file included from /usr/share/rvm/src/rbx-3.100/machine/memory/header.hpp:18:
In file included from /usr/share/rvm/src/rbx-3.100/machine/util/thread.hpp:17:
In file included from /usr/include/c++/v1/sstream:174:
In file included from /usr/include/c++/v1/ostream:138:
In file included from /usr/include/c++/v1/ios:216:
/usr/include/c++/v1/__locale:39:11: fatal error: 'xlocale.h' file not found
# include <xlocale.h>
          ^~~~~~~~~~~
In file included from machine/bytecode_verifier.cpp:1:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/compiled_code.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/object_utils.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/object.hpp:7:
In file included from /usr/share/rvm/src/rbx-3.100/machine/memory/header.hpp:18:
In file included from /usr/share/rvm/src/rbx-3.100/machine/util/thread.hpp:17:
In file included from /usr/include/c++/v1/sstream:174:
In file included from /usr/include/c++/v1/ostream:138:
In file included from /usr/include/c++/v1/ios:216:
/usr/include/c++/v1/__locale:39:11: fatal error: 'xlocale.h' file not found
# include <xlocale.h>
          ^~~~~~~~~~~
In file included from machine/accessor_primitives.cpp:1:
In file included from /usr/share/rvm/src/rbx-3.100/machine/arguments.hpp:5:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/array.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/object_utils.hpp:4:
In file included from /usr/share/rvm/src/rbx-3.100/machine/class/object.hpp:7:
In file included from /usr/share/rvm/src/rbx-3.100/machine/memory/header.hpp:18:
In file included from /usr/share/rvm/src/rbx-3.100/machine/util/thread.hpp:17:
In file included from /usr/include/c++/v1/sstream:174:
In file included from /usr/include/c++/v1/ostream:138:
In file included from /usr/include/c++/v1/ios:216:
/usr/include/c++/v1/__locale:39:11: fatal error: 'xlocale.h' file not found
# include <xlocale.h>
          ^~~~~~~~~~~
1 error generated.
```

Yet according to [Ubuntu](https://packages.ubuntu.com/search?searchon=contents&keywords=xlocale.h&mode=exactfilename&suite=artful&arch=any) that file comes with `libc++-dev`, so hmm... Possibly a missing `-I` or something.

**Comment by CpuID** [comment] 2018-03-13 23:45
Interesting, the `xlocale.h` issue smells a lot like [this upstream Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/libc++/+bug/1725858) that was recently fixed...

**Comment by CpuID** [comment] 2018-03-14 00:00
Woohoo, installed RBX 3.100.

So, the first fix:

```
sudo apt-get install libc++-dev libc++abi-dev
```

And the second fix confirmed, [the upstream Ubuntu issue workaround](https://bugs.launchpad.net/ubuntu/+source/libc++/+bug/1725858) does it.

I used the included workaround (maybe this can go in `requirements/ubuntu` as a conditional `if [ ! -f "/usr/include/xlocale.h" ]; then`?

```
cd /usr/include && sudo ln -s locale.h xlocale.h
```

**Comment by pkuczynski** [comment] 2018-03-14 00:33
I added `libc++-dev libc++abi-dev` to the deps, but I dont think we can create links in `/usr/include`. @mpapis any idea?

**Comment by CpuID** [comment] 2018-03-14 01:56
Just to confirm the [LLVM PPA](http://apt.llvm.org/) does not include libc++.

We would ideally want something like [this PPA](https://launchpad.net/~anthony-justsoftwaresolutions/+archive/ubuntu/libcxx) but with >16.04 packages in it (not included). Can't seem to find one out there right now, the next best option would be creating a custom PPA.

Just to confirm - what would the implications be of having an interactive prompt within `requirements/ubuntu` that does the symlink workaround above, and warns the user beforehand of the system impact etc? Interactive prompts are already used for passwords for `apt-get` and friends.

Looks like that specific file is not included in any standardised include paths, according to [packages.ubuntu.com](https://packages.ubuntu.com/search?searchon=contents&keywords=xlocale.h&mode=exactfilename&suite=artful&arch=any) so the conflict risk feels low...

**Comment by pkuczynski** [comment] 2018-03-14 09:24
I still don't think creating symlinks in `/usr/include` is the right approach...

**Comment by CpuID** [comment] 2018-03-14 09:36
@pkuczynski fair call...

Being that it's the libc++ upstream that has a bug, I think our hands are tied unless we use/setup a PPA with a forked `libc++1`/`libc++-dev` - concur? Looking at the stack trace, it's an include within the upstream that actually causes the failures...

Not sure what other alternatives we have here, other than maybe installing a non-system libc++ (alternate paths?) and pointing RBX at it via `configure` options, to ensure no breakage to other Ubuntu packages on the system?

**Comment by pkuczynski** [comment] 2018-03-30 10:10
I merged this PR in. We will wait for the upstream to apply fixes...

**Closed** 2018-03-30 10:09 UTC
Labels: feedback needed, platform: ubuntu
