### ISSUE TITLE
erro in rvm requirements

### ISSUE THREAD

**Issue by reiTT** [rvm/rvm#3523] opened 2015-10-10 01:40 UTC
Error running 'requirements_debian_update_system ruby-2.2.1',
showing last 15 lines of /home/bruno/.rvm/log/1444440787_ruby-2.2.1/update_system.log
++ /scripts/functions/logging : rvm_pretty_print()  78 > case "${TERM:-dumb}" in
++ /scripts/functions/logging : rvm_pretty_print()  81 > case "$1" in
++ /scripts/functions/logging : rvm_pretty_print()  83 > [[ -t 2 ]]
++ /scripts/functions/logging : rvm_pretty_print()  83 > return 1
++ /scripts/functions/logging : rvm_error()  117 > printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/_.list
\n'
There has been error while updating 'apt-get', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/_.list

++ /scripts/functions/requirements/ubuntu : requirements_debian_update_system()  53 > return 100
Requirements installation failed with status: 100.

**Comment by pkuczynski** [comment] 2016-11-07 10:49
Is this still happening for you even with `rvm get master`

**Comment by legitdealer** [comment] 2016-12-02 23:32
I'm still having some troubles : 

root@kali:~# rvm install 2.1.5
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system...........................................................................................................|
Error running 'requirements_debian_update_system ruby-2.1.5',
showing last 15 lines of /usr/local/rvm/log/1480721323_ruby-2.1.5/update_system.log
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 2 ]]
++ return 1
++ printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list
\n'
There has been error while updating 'apt-get', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

++ return 100

im using kali linux on my mac i think i need to remove the errors from : 
/etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

but i don't know how :| please help

**Comment by pkuczynski** [comment] 2017-04-12 23:26
Check manually if running `apt-get update` is causing any errors? Most likely it does. You might find this article useful: http://www.sachingevariya.com/2015/08/requirementsdebianupdatesystem-ruby-222.html

**Comment by pkuczynski** [comment] 2017-04-12 23:26
Closing as duplicate of #3411

**Closed by pkuczynski** 2017-04-12 23:26 UTC
Labels: platform: debian
